// @generated by cargo xtask codegen --typescript
// DO NOT EDIT — regenerate with `cargo xtask codegen --typescript`

export type ConnectionId = bigint;

export interface ProtocolError {
  description: string;
}

export type Parity =
  | { tag: "Odd" }
  | { tag: "Even" };

export interface ConnectionSettings {
  parity: Parity;
  max_concurrent_requests: number;
  initial_channel_credit: number;
}

export type MetadataValue =
  | { tag: "String"; value: string }
  | { tag: "Bytes"; value: Uint8Array }
  | { tag: "U64"; value: bigint };

export type MetadataFlags = bigint;

export interface MetadataEntry {
  key: string;
  value: MetadataValue;
  flags: MetadataFlags;
}

export interface ConnectionOpen {
  connection_settings: ConnectionSettings;
  metadata: MetadataEntry[];
}

export interface ConnectionAccept {
  connection_settings: ConnectionSettings;
  metadata: MetadataEntry[];
}

export interface ConnectionReject {
  metadata: MetadataEntry[];
}

export interface ConnectionClose {
  metadata: MetadataEntry[];
}

export type RequestId = bigint;

export type MethodId = bigint;

export type SchemaPayloadBytes = Uint8Array;

export interface RequestCall {
  method_id: MethodId;
  metadata: MetadataEntry[];
  args: Uint8Array;
  schemas: SchemaPayloadBytes;
}

export interface RequestResponse {
  metadata: MetadataEntry[];
  ret: Uint8Array;
  schemas: SchemaPayloadBytes;
}

export interface RequestCancel {
  metadata: MetadataEntry[];
}

export type RequestBody =
  | { tag: "Call"; value: RequestCall }
  | { tag: "Response"; value: RequestResponse }
  | { tag: "Cancel"; value: RequestCancel };

export interface RequestMessage {
  id: RequestId;
  body: RequestBody;
}

export type BindingDirection =
  | { tag: "Args" }
  | { tag: "Response" };

export interface SchemaMessage {
  method_id: MethodId;
  direction: BindingDirection;
  schemas: SchemaPayloadBytes;
}

export type ChannelId = bigint;

export interface ChannelItem {
  item: Uint8Array;
}

export interface ChannelClose {
  metadata: MetadataEntry[];
}

export interface ChannelReset {
  metadata: MetadataEntry[];
}

export interface ChannelGrantCredit {
  additional: number;
}

export type ChannelBody =
  | { tag: "Item"; value: ChannelItem }
  | { tag: "Close"; value: ChannelClose }
  | { tag: "Reset"; value: ChannelReset }
  | { tag: "GrantCredit"; value: ChannelGrantCredit };

export interface ChannelMessage {
  id: ChannelId;
  body: ChannelBody;
}

export interface Ping {
  nonce: bigint;
}

export interface Pong {
  nonce: bigint;
}

export type MessagePayload =
  | { tag: "ProtocolError"; value: ProtocolError }
  | { tag: "ConnectionOpen"; value: ConnectionOpen }
  | { tag: "ConnectionAccept"; value: ConnectionAccept }
  | { tag: "ConnectionReject"; value: ConnectionReject }
  | { tag: "ConnectionClose"; value: ConnectionClose }
  | { tag: "RequestMessage"; value: RequestMessage }
  | { tag: "SchemaMessage"; value: SchemaMessage }
  | { tag: "ChannelMessage"; value: ChannelMessage }
  | { tag: "Ping"; value: Ping }
  | { tag: "Pong"; value: Pong };

export interface Message {
  connection_id: ConnectionId;
  payload: MessagePayload;
}

export type SchemaHash = bigint;

export type TypeParamName = string;

export type TypeRef =
  | { tag: "Concrete"; type_id: SchemaHash; args: TypeRef[] }
  | { tag: "Var"; name: TypeParamName };

export interface FieldSchema {
  name: string;
  type_ref: TypeRef;
  required: boolean;
}

export type VariantPayload =
  | { tag: "Unit" }
  | { tag: "Newtype"; type_ref: TypeRef }
  | { tag: "Tuple"; types: TypeRef[] }
  | { tag: "Struct"; fields: FieldSchema[] };

export interface VariantSchema {
  name: string;
  index: number;
  payload: VariantPayload;
}

export type ChannelDirection =
  | { tag: "Tx" }
  | { tag: "Rx" };

export type PrimitiveType =
  | { tag: "Bool" }
  | { tag: "U8" }
  | { tag: "U16" }
  | { tag: "U32" }
  | { tag: "U64" }
  | { tag: "U128" }
  | { tag: "I8" }
  | { tag: "I16" }
  | { tag: "I32" }
  | { tag: "I64" }
  | { tag: "I128" }
  | { tag: "F32" }
  | { tag: "F64" }
  | { tag: "Char" }
  | { tag: "String" }
  | { tag: "Unit" }
  | { tag: "Never" }
  | { tag: "Bytes" }
  | { tag: "Payload" };

export type SchemaKind =
  | { tag: "Struct"; name: string; fields: FieldSchema[] }
  | { tag: "Enum"; name: string; variants: VariantSchema[] }
  | { tag: "Tuple"; elements: TypeRef[] }
  | { tag: "List"; element: TypeRef }
  | { tag: "Map"; key: TypeRef; value: TypeRef }
  | { tag: "Array"; element: TypeRef; length: bigint }
  | { tag: "Option"; element: TypeRef }
  | { tag: "Channel"; direction: ChannelDirection; element: TypeRef }
  | { tag: "Primitive"; primitive_type: PrimitiveType };

export interface Schema {
  id: SchemaHash;
  type_params: TypeParamName[];
  kind: SchemaKind;
}

export interface ResumeKeyBytes {
  bytes: Uint8Array;
}

export interface Hello {
  parity: Parity;
  connection_settings: ConnectionSettings;
  message_payload_schema: Schema[];
  supports_retry: boolean;
  resume_key: ResumeKeyBytes | null;
  metadata: MetadataEntry[];
}

export interface HelloYourself {
  connection_settings: ConnectionSettings;
  message_payload_schema: Schema[];
  supports_retry: boolean;
  resume_key: ResumeKeyBytes | null;
  metadata: MetadataEntry[];
}

export interface LetsGo {
}

export interface Sorry {
  reason: string;
}

export type HandshakeMessage =
  | { tag: "Hello"; value: Hello }
  | { tag: "HelloYourself"; value: HelloYourself }
  | { tag: "LetsGo"; value: LetsGo }
  | { tag: "Sorry"; value: Sorry };

export interface SchemaPayload {
  schemas: Schema[];
  root: TypeRef;
}

export const ParityDiscriminant = {
  Odd: 0,
  Even: 1,
} as const;

export const MetadataValueDiscriminant = {
  String: 0,
  Bytes: 1,
  U64: 2,
} as const;

export const RequestBodyDiscriminant = {
  Call: 0,
  Response: 1,
  Cancel: 2,
} as const;

export const BindingDirectionDiscriminant = {
  Args: 0,
  Response: 1,
} as const;

export const ChannelBodyDiscriminant = {
  Item: 0,
  Close: 1,
  Reset: 2,
  GrantCredit: 3,
} as const;

export const MessagePayloadDiscriminant = {
  ProtocolError: 0,
  ConnectionOpen: 1,
  ConnectionAccept: 2,
  ConnectionReject: 3,
  ConnectionClose: 4,
  RequestMessage: 5,
  SchemaMessage: 6,
  ChannelMessage: 7,
  Ping: 8,
  Pong: 9,
} as const;

export const TypeRefDiscriminant = {
  Concrete: 0,
  Var: 1,
} as const;

export const VariantPayloadDiscriminant = {
  Unit: 0,
  Newtype: 1,
  Tuple: 2,
  Struct: 3,
} as const;

export const ChannelDirectionDiscriminant = {
  Tx: 0,
  Rx: 1,
} as const;

export const PrimitiveTypeDiscriminant = {
  Bool: 0,
  U8: 1,
  U16: 2,
  U32: 3,
  U64: 4,
  U128: 5,
  I8: 6,
  I16: 7,
  I32: 8,
  I64: 9,
  I128: 10,
  F32: 11,
  F64: 12,
  Char: 13,
  String: 14,
  Unit: 15,
  Never: 16,
  Bytes: 17,
  Payload: 18,
} as const;

export const SchemaKindDiscriminant = {
  Struct: 0,
  Enum: 1,
  Tuple: 2,
  List: 3,
  Map: 4,
  Array: 5,
  Option: 6,
  Channel: 7,
  Primitive: 8,
} as const;

export const HandshakeMessageDiscriminant = {
  Hello: 0,
  HelloYourself: 1,
  LetsGo: 2,
  Sorry: 3,
} as const;

export type ParityOdd = Extract<Parity, { tag: "Odd" }>;
export type ParityEven = Extract<Parity, { tag: "Even" }>;

export type MetadataValueString = Extract<MetadataValue, { tag: "String" }>;
export type MetadataValueBytes = Extract<MetadataValue, { tag: "Bytes" }>;
export type MetadataValueU64 = Extract<MetadataValue, { tag: "U64" }>;

export type RequestBodyCall = Extract<RequestBody, { tag: "Call" }>;
export type RequestBodyResponse = Extract<RequestBody, { tag: "Response" }>;
export type RequestBodyCancel = Extract<RequestBody, { tag: "Cancel" }>;

export type BindingDirectionArgs = Extract<BindingDirection, { tag: "Args" }>;
export type BindingDirectionResponse = Extract<BindingDirection, { tag: "Response" }>;

export type ChannelBodyItem = Extract<ChannelBody, { tag: "Item" }>;
export type ChannelBodyClose = Extract<ChannelBody, { tag: "Close" }>;
export type ChannelBodyReset = Extract<ChannelBody, { tag: "Reset" }>;
export type ChannelBodyGrantCredit = Extract<ChannelBody, { tag: "GrantCredit" }>;

export type MessagePayloadProtocolError = Extract<MessagePayload, { tag: "ProtocolError" }>;
export type MessagePayloadConnectionOpen = Extract<MessagePayload, { tag: "ConnectionOpen" }>;
export type MessagePayloadConnectionAccept = Extract<MessagePayload, { tag: "ConnectionAccept" }>;
export type MessagePayloadConnectionReject = Extract<MessagePayload, { tag: "ConnectionReject" }>;
export type MessagePayloadConnectionClose = Extract<MessagePayload, { tag: "ConnectionClose" }>;
export type MessagePayloadRequestMessage = Extract<MessagePayload, { tag: "RequestMessage" }>;
export type MessagePayloadSchemaMessage = Extract<MessagePayload, { tag: "SchemaMessage" }>;
export type MessagePayloadChannelMessage = Extract<MessagePayload, { tag: "ChannelMessage" }>;
export type MessagePayloadPing = Extract<MessagePayload, { tag: "Ping" }>;
export type MessagePayloadPong = Extract<MessagePayload, { tag: "Pong" }>;

export type TypeRefConcrete = Extract<TypeRef, { tag: "Concrete" }>;
export type TypeRefVar = Extract<TypeRef, { tag: "Var" }>;

export type VariantPayloadUnit = Extract<VariantPayload, { tag: "Unit" }>;
export type VariantPayloadNewtype = Extract<VariantPayload, { tag: "Newtype" }>;
export type VariantPayloadTuple = Extract<VariantPayload, { tag: "Tuple" }>;
export type VariantPayloadStruct = Extract<VariantPayload, { tag: "Struct" }>;

export type ChannelDirectionTx = Extract<ChannelDirection, { tag: "Tx" }>;
export type ChannelDirectionRx = Extract<ChannelDirection, { tag: "Rx" }>;

export type PrimitiveTypeBool = Extract<PrimitiveType, { tag: "Bool" }>;
export type PrimitiveTypeU8 = Extract<PrimitiveType, { tag: "U8" }>;
export type PrimitiveTypeU16 = Extract<PrimitiveType, { tag: "U16" }>;
export type PrimitiveTypeU32 = Extract<PrimitiveType, { tag: "U32" }>;
export type PrimitiveTypeU64 = Extract<PrimitiveType, { tag: "U64" }>;
export type PrimitiveTypeU128 = Extract<PrimitiveType, { tag: "U128" }>;
export type PrimitiveTypeI8 = Extract<PrimitiveType, { tag: "I8" }>;
export type PrimitiveTypeI16 = Extract<PrimitiveType, { tag: "I16" }>;
export type PrimitiveTypeI32 = Extract<PrimitiveType, { tag: "I32" }>;
export type PrimitiveTypeI64 = Extract<PrimitiveType, { tag: "I64" }>;
export type PrimitiveTypeI128 = Extract<PrimitiveType, { tag: "I128" }>;
export type PrimitiveTypeF32 = Extract<PrimitiveType, { tag: "F32" }>;
export type PrimitiveTypeF64 = Extract<PrimitiveType, { tag: "F64" }>;
export type PrimitiveTypeChar = Extract<PrimitiveType, { tag: "Char" }>;
export type PrimitiveTypeString = Extract<PrimitiveType, { tag: "String" }>;
export type PrimitiveTypeUnit = Extract<PrimitiveType, { tag: "Unit" }>;
export type PrimitiveTypeNever = Extract<PrimitiveType, { tag: "Never" }>;
export type PrimitiveTypeBytes = Extract<PrimitiveType, { tag: "Bytes" }>;
export type PrimitiveTypePayload = Extract<PrimitiveType, { tag: "Payload" }>;

export type SchemaKindStruct = Extract<SchemaKind, { tag: "Struct" }>;
export type SchemaKindEnum = Extract<SchemaKind, { tag: "Enum" }>;
export type SchemaKindTuple = Extract<SchemaKind, { tag: "Tuple" }>;
export type SchemaKindList = Extract<SchemaKind, { tag: "List" }>;
export type SchemaKindMap = Extract<SchemaKind, { tag: "Map" }>;
export type SchemaKindArray = Extract<SchemaKind, { tag: "Array" }>;
export type SchemaKindOption = Extract<SchemaKind, { tag: "Option" }>;
export type SchemaKindChannel = Extract<SchemaKind, { tag: "Channel" }>;
export type SchemaKindPrimitive = Extract<SchemaKind, { tag: "Primitive" }>;

export type HandshakeMessageHello = Extract<HandshakeMessage, { tag: "Hello" }>;
export type HandshakeMessageHelloYourself = Extract<HandshakeMessage, { tag: "HelloYourself" }>;
export type HandshakeMessageLetsGo = Extract<HandshakeMessage, { tag: "LetsGo" }>;
export type HandshakeMessageSorry = Extract<HandshakeMessage, { tag: "Sorry" }>;

export const messageSchemaRegistry: import("@bearcove/binette").SchemaRegistry = new Map<
  bigint,
  import("@bearcove/binette").Schema
>([
  [15651524488059042220n, {
    id: 0xd9356298b81639acn,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "u64" },
  }],
  [7889689245711945960n, {
    id: 0x6d7dce914ee150e8n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "string" },
  }],
  [3673619088650892597n, {
    id: 0x32fb5118f3217535n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ProtocolError",
      fields: [{
        name: "description",
        type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] },
        required: true,
      }],
    },
  }],
  [6562566395840718674n, {
    id: 0x5b12eb5df7006752n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "Parity",
      variants: [{ name: "Odd", index: 0, payload: { tag: "unit" } }, {
        name: "Even",
        index: 1,
        payload: { tag: "unit" },
      }],
    },
  }],
  [2890286099751396276n, {
    id: 0x281c5be4f2ee63b4n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "u32" },
  }],
  [9126347097505338775n, {
    id: 0x7ea74c54ebb91597n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ConnectionSettings",
      fields: [{
        name: "parity",
        type_ref: { tag: "concrete", type_id: 0x5b12eb5df7006752n, args: [] },
        required: true,
      }, {
        name: "max_concurrent_requests",
        type_ref: { tag: "concrete", type_id: 0x281c5be4f2ee63b4n, args: [] },
        required: true,
      }, {
        name: "initial_channel_credit",
        type_ref: { tag: "concrete", type_id: 0x281c5be4f2ee63b4n, args: [] },
        required: false,
      }],
    },
  }],
  [13439064026636322996n, {
    id: 0xba8125876d6388b4n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "bytes" },
  }],
  [13364648597510457213n, {
    id: 0xb978c5172a88877dn,
    type_params: [],
    kind: {
      tag: "enum",
      name: "MetadataValue",
      variants: [{
        name: "String",
        index: 0,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] } },
      }, {
        name: "Bytes",
        index: 1,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xba8125876d6388b4n, args: [] } },
      }, {
        name: "U64",
        index: 2,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] } },
      }],
    },
  }],
  [11696295240458254911n, {
    id: 0xa251968d339b3a3fn,
    type_params: [],
    kind: {
      tag: "struct",
      name: "MetadataEntry",
      fields: [{ name: "key", type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, {
        name: "value",
        type_ref: { tag: "concrete", type_id: 0xb978c5172a88877dn, args: [] },
        required: true,
      }, { name: "flags", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }, required: true }],
    },
  }],
  [762995119192776039n, {
    id: 0x0a96b404b4d79d67n,
    type_params: ["T"],
    kind: { tag: "list", element: { tag: "var", name: "T" } },
  }],
  [1204994708329552153n, {
    id: 0x10b9004d8a355919n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ConnectionOpen",
      fields: [{
        name: "connection_settings",
        type_ref: { tag: "concrete", type_id: 0x7ea74c54ebb91597n, args: [] },
        required: true,
      }, {
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [18216330864927883159n, {
    id: 0xfccd68684b02bf97n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ConnectionAccept",
      fields: [{
        name: "connection_settings",
        type_ref: { tag: "concrete", type_id: 0x7ea74c54ebb91597n, args: [] },
        required: true,
      }, {
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [390445051956246116n, {
    id: 0x056b23b4c2293664n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ConnectionReject",
      fields: [{
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [16730277026633520892n, {
    id: 0xe82de2509e5e96fcn,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ConnectionClose",
      fields: [{
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [9907609158461142822n, {
    id: 0x897ee6096f7bb726n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "payload" },
  }],
  [3210315508570984224n, {
    id: 0x2c8d54f2314d0f20n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "u8" },
  }],
  [2327808632475989147n, {
    id: 0x204e099e33d1b49bn,
    type_params: [],
    kind: {
      tag: "struct",
      name: "RequestCall",
      fields: [
        { name: "method_id", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }, required: true },
        {
          name: "metadata",
          type_ref: {
            tag: "concrete",
            type_id: 0x0a96b404b4d79d67n,
            args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
          },
          required: true,
        },
        { name: "args", type_ref: { tag: "concrete", type_id: 0x897ee6096f7bb726n, args: [] }, required: true },
        {
          name: "schemas",
          type_ref: {
            tag: "concrete",
            type_id: 0x0a96b404b4d79d67n,
            args: [{ tag: "concrete", type_id: 0x2c8d54f2314d0f20n, args: [] }],
          },
          required: true,
        },
      ],
    },
  }],
  [7887728775982478321n, {
    id: 0x6d76d787e10ff3f1n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "RequestResponse",
      fields: [
        {
          name: "metadata",
          type_ref: {
            tag: "concrete",
            type_id: 0x0a96b404b4d79d67n,
            args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
          },
          required: true,
        },
        { name: "ret", type_ref: { tag: "concrete", type_id: 0x897ee6096f7bb726n, args: [] }, required: true },
        {
          name: "schemas",
          type_ref: {
            tag: "concrete",
            type_id: 0x0a96b404b4d79d67n,
            args: [{ tag: "concrete", type_id: 0x2c8d54f2314d0f20n, args: [] }],
          },
          required: true,
        },
      ],
    },
  }],
  [15588907070673503211n, {
    id: 0xd856ec632011c3ebn,
    type_params: [],
    kind: {
      tag: "struct",
      name: "RequestCancel",
      fields: [{
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [15762469341685469490n, {
    id: 0xdabf8a5a6625d132n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "RequestBody",
      variants: [{
        name: "Call",
        index: 0,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x204e099e33d1b49bn, args: [] } },
      }, {
        name: "Response",
        index: 1,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x6d76d787e10ff3f1n, args: [] } },
      }, {
        name: "Cancel",
        index: 2,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xd856ec632011c3ebn, args: [] } },
      }],
    },
  }],
  [14895311984549778772n, {
    id: 0xceb6c754c9b55554n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "RequestMessage",
      fields: [{ name: "id", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }, required: true }, {
        name: "body",
        type_ref: { tag: "concrete", type_id: 0xdabf8a5a6625d132n, args: [] },
        required: true,
      }],
    },
  }],
  [17730792173009085514n, {
    id: 0xf6106d8a227ba44an,
    type_params: [],
    kind: {
      tag: "enum",
      name: "BindingDirection",
      variants: [{ name: "Args", index: 0, payload: { tag: "unit" } }, {
        name: "Response",
        index: 1,
        payload: { tag: "unit" },
      }],
    },
  }],
  [5184886609598851775n, {
    id: 0x47f46ae695d1aabfn,
    type_params: [],
    kind: {
      tag: "struct",
      name: "SchemaMessage",
      fields: [
        { name: "method_id", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }, required: true },
        { name: "direction", type_ref: { tag: "concrete", type_id: 0xf6106d8a227ba44an, args: [] }, required: true },
        {
          name: "schemas",
          type_ref: {
            tag: "concrete",
            type_id: 0x0a96b404b4d79d67n,
            args: [{ tag: "concrete", type_id: 0x2c8d54f2314d0f20n, args: [] }],
          },
          required: true,
        },
      ],
    },
  }],
  [807395325490607072n, {
    id: 0x0b3471c5512db3e0n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ChannelItem",
      fields: [{ name: "item", type_ref: { tag: "concrete", type_id: 0x897ee6096f7bb726n, args: [] }, required: true }],
    },
  }],
  [2341051947520352743n, {
    id: 0x207d1657c4afe1e7n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ChannelClose",
      fields: [{
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [13893128806027145045n, {
    id: 0xc0ce4f0a45feaf55n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ChannelReset",
      fields: [{
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [11287018253931848275n, {
    id: 0x9ca38b4cfef52253n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ChannelGrantCredit",
      fields: [{
        name: "additional",
        type_ref: { tag: "concrete", type_id: 0x281c5be4f2ee63b4n, args: [] },
        required: true,
      }],
    },
  }],
  [13967719957911777940n, {
    id: 0xc1d74f4c2d773294n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "ChannelBody",
      variants: [{
        name: "Item",
        index: 0,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x0b3471c5512db3e0n, args: [] } },
      }, {
        name: "Close",
        index: 1,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x207d1657c4afe1e7n, args: [] } },
      }, {
        name: "Reset",
        index: 2,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xc0ce4f0a45feaf55n, args: [] } },
      }, {
        name: "GrantCredit",
        index: 3,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x9ca38b4cfef52253n, args: [] } },
      }],
    },
  }],
  [340696210971267763n, {
    id: 0x04ba6566174392b3n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ChannelMessage",
      fields: [{ name: "id", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }, required: true }, {
        name: "body",
        type_ref: { tag: "concrete", type_id: 0xc1d74f4c2d773294n, args: [] },
        required: true,
      }],
    },
  }],
  [7846509427421105468n, {
    id: 0x6ce466c06c304d3cn,
    type_params: [],
    kind: {
      tag: "struct",
      name: "Ping",
      fields: [{
        name: "nonce",
        type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] },
        required: true,
      }],
    },
  }],
  [6013976564896838672n, {
    id: 0x5375efd286333410n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "Pong",
      fields: [{
        name: "nonce",
        type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] },
        required: true,
      }],
    },
  }],
  [11404656770198272752n, {
    id: 0x9e457ae874ebfaf0n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "MessagePayload",
      variants: [{
        name: "ProtocolError",
        index: 0,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x32fb5118f3217535n, args: [] } },
      }, {
        name: "ConnectionOpen",
        index: 1,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x10b9004d8a355919n, args: [] } },
      }, {
        name: "ConnectionAccept",
        index: 2,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xfccd68684b02bf97n, args: [] } },
      }, {
        name: "ConnectionReject",
        index: 3,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x056b23b4c2293664n, args: [] } },
      }, {
        name: "ConnectionClose",
        index: 4,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xe82de2509e5e96fcn, args: [] } },
      }, {
        name: "RequestMessage",
        index: 5,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xceb6c754c9b55554n, args: [] } },
      }, {
        name: "SchemaMessage",
        index: 6,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x47f46ae695d1aabfn, args: [] } },
      }, {
        name: "ChannelMessage",
        index: 7,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x04ba6566174392b3n, args: [] } },
      }, {
        name: "Ping",
        index: 8,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x6ce466c06c304d3cn, args: [] } },
      }, {
        name: "Pong",
        index: 9,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x5375efd286333410n, args: [] } },
      }],
    },
  }],
  [1533027651292629175n, {
    id: 0x15466886ca2608b7n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "Message",
      fields: [{
        name: "connection_id",
        type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] },
        required: true,
      }, { name: "payload", type_ref: { tag: "concrete", type_id: 0x9e457ae874ebfaf0n, args: [] }, required: true }],
    },
  }],
]);

export const messageRootRef: import("@bearcove/binette").TypeRef = {
  tag: "concrete",
  type_id: 0x15466886ca2608b7n,
  args: [],
};

export const messageSchemas: import("@bearcove/binette").Schema[] = Array.from(messageSchemaRegistry.values());

export const handshakeMessageSchemaRegistry: import("@bearcove/binette").SchemaRegistry = new Map<
  bigint,
  import("@bearcove/binette").Schema
>([
  [6562566395840718674n, {
    id: 0x5b12eb5df7006752n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "Parity",
      variants: [{ name: "Odd", index: 0, payload: { tag: "unit" } }, {
        name: "Even",
        index: 1,
        payload: { tag: "unit" },
      }],
    },
  }],
  [2890286099751396276n, {
    id: 0x281c5be4f2ee63b4n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "u32" },
  }],
  [9126347097505338775n, {
    id: 0x7ea74c54ebb91597n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ConnectionSettings",
      fields: [{
        name: "parity",
        type_ref: { tag: "concrete", type_id: 0x5b12eb5df7006752n, args: [] },
        required: true,
      }, {
        name: "max_concurrent_requests",
        type_ref: { tag: "concrete", type_id: 0x281c5be4f2ee63b4n, args: [] },
        required: true,
      }, {
        name: "initial_channel_credit",
        type_ref: { tag: "concrete", type_id: 0x281c5be4f2ee63b4n, args: [] },
        required: false,
      }],
    },
  }],
  [15651524488059042220n, {
    id: 0xd9356298b81639acn,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "u64" },
  }],
  [7889689245711945960n, {
    id: 0x6d7dce914ee150e8n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "string" },
  }],
  [762995119192776039n, {
    id: 0x0a96b404b4d79d67n,
    type_params: ["T"],
    kind: { tag: "list", element: { tag: "var", name: "T" } },
  }],
  [16913039315790463384n, {
    id: 0xeab72fa609e80198n,
    type_params: ["Id"],
    kind: {
      tag: "enum",
      name: "TypeRef",
      variants: [{
        name: "Concrete",
        index: 0,
        payload: {
          tag: "struct",
          fields: [{ name: "type_id", type_ref: { tag: "var", name: "Id" }, required: true }, {
            name: "args",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xeab72fa609e80198n,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "Var",
        index: 1,
        payload: {
          tag: "struct",
          fields: [{
            name: "name",
            type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] },
            required: true,
          }],
        },
      }],
    },
  }],
  [1694311858211060550n, {
    id: 0x178367a87f66fb46n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "bool" },
  }],
  [15084366699922010430n, {
    id: 0xd1566f97da95313en,
    type_params: ["Id"],
    kind: {
      tag: "struct",
      name: "FieldSchema",
      fields: [
        { name: "name", type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] }, required: true },
        {
          name: "type_ref",
          type_ref: {
            tag: "concrete",
            type_id: 0xeab72fa609e80198n,
            args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
          },
          required: true,
        },
        { name: "required", type_ref: { tag: "concrete", type_id: 0x178367a87f66fb46n, args: [] }, required: true },
      ],
    },
  }],
  [2581015269456384018n, {
    id: 0x23d19bb677ce9012n,
    type_params: ["Id"],
    kind: {
      tag: "enum",
      name: "VariantPayload",
      variants: [{ name: "Unit", index: 0, payload: { tag: "unit" } }, {
        name: "Newtype",
        index: 1,
        payload: {
          tag: "struct",
          fields: [{
            name: "type_ref",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Tuple",
        index: 2,
        payload: {
          tag: "struct",
          fields: [{
            name: "types",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xeab72fa609e80198n,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "Struct",
        index: 3,
        payload: {
          tag: "struct",
          fields: [{
            name: "fields",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xd1566f97da95313en,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }],
    },
  }],
  [8321007665563425864n, {
    id: 0x737a28629f35dc48n,
    type_params: ["Id"],
    kind: {
      tag: "struct",
      name: "VariantSchema",
      fields: [
        { name: "name", type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] }, required: true },
        { name: "index", type_ref: { tag: "concrete", type_id: 0x281c5be4f2ee63b4n, args: [] }, required: true },
        {
          name: "payload",
          type_ref: {
            tag: "concrete",
            type_id: 0x23d19bb677ce9012n,
            args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
          },
          required: true,
        },
      ],
    },
  }],
  [9922667967649487168n, {
    id: 0x89b465f1abe51940n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "ChannelDirection",
      variants: [{ name: "Tx", index: 0, payload: { tag: "unit" } }, {
        name: "Rx",
        index: 1,
        payload: { tag: "unit" },
      }],
    },
  }],
  [9820435852653867365n, {
    id: 0x8849326088f1b165n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "PrimitiveType",
      variants: [
        { name: "Bool", index: 0, payload: { tag: "unit" } },
        { name: "U8", index: 1, payload: { tag: "unit" } },
        { name: "U16", index: 2, payload: { tag: "unit" } },
        { name: "U32", index: 3, payload: { tag: "unit" } },
        { name: "U64", index: 4, payload: { tag: "unit" } },
        { name: "U128", index: 5, payload: { tag: "unit" } },
        { name: "I8", index: 6, payload: { tag: "unit" } },
        { name: "I16", index: 7, payload: { tag: "unit" } },
        { name: "I32", index: 8, payload: { tag: "unit" } },
        { name: "I64", index: 9, payload: { tag: "unit" } },
        { name: "I128", index: 10, payload: { tag: "unit" } },
        { name: "F32", index: 11, payload: { tag: "unit" } },
        { name: "F64", index: 12, payload: { tag: "unit" } },
        { name: "Char", index: 13, payload: { tag: "unit" } },
        { name: "String", index: 14, payload: { tag: "unit" } },
        { name: "Unit", index: 15, payload: { tag: "unit" } },
        { name: "Never", index: 16, payload: { tag: "unit" } },
        { name: "Bytes", index: 17, payload: { tag: "unit" } },
        { name: "Payload", index: 18, payload: { tag: "unit" } },
      ],
    },
  }],
  [14647032924436458309n, {
    id: 0xcb44b6d76a7c6b45n,
    type_params: ["Id"],
    kind: {
      tag: "enum",
      name: "SchemaKind",
      variants: [{
        name: "Struct",
        index: 0,
        payload: {
          tag: "struct",
          fields: [{
            name: "name",
            type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] },
            required: true,
          }, {
            name: "fields",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xd1566f97da95313en,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "Enum",
        index: 1,
        payload: {
          tag: "struct",
          fields: [{
            name: "name",
            type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] },
            required: true,
          }, {
            name: "variants",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0x737a28629f35dc48n,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "Tuple",
        index: 2,
        payload: {
          tag: "struct",
          fields: [{
            name: "elements",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xeab72fa609e80198n,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "List",
        index: 3,
        payload: {
          tag: "struct",
          fields: [{
            name: "element",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Map",
        index: 4,
        payload: {
          tag: "struct",
          fields: [{
            name: "key",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }, {
            name: "value",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Array",
        index: 5,
        payload: {
          tag: "struct",
          fields: [{
            name: "element",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }, { name: "length", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }, required: true }],
        },
      }, {
        name: "Option",
        index: 6,
        payload: {
          tag: "struct",
          fields: [{
            name: "element",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Channel",
        index: 7,
        payload: {
          tag: "struct",
          fields: [{
            name: "direction",
            type_ref: { tag: "concrete", type_id: 0x89b465f1abe51940n, args: [] },
            required: true,
          }, {
            name: "element",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Primitive",
        index: 8,
        payload: {
          tag: "struct",
          fields: [{
            name: "primitive_type",
            type_ref: { tag: "concrete", type_id: 0x8849326088f1b165n, args: [] },
            required: true,
          }],
        },
      }],
    },
  }],
  [4589520839594691869n, {
    id: 0x3fb140e3254b4d1dn,
    type_params: ["Id"],
    kind: {
      tag: "struct",
      name: "Schema",
      fields: [{ name: "id", type_ref: { tag: "var", name: "Id" }, required: true }, {
        name: "type_params",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] }],
        },
        required: false,
      }, {
        name: "kind",
        type_ref: {
          tag: "concrete",
          type_id: 0xcb44b6d76a7c6b45n,
          args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [3210315508570984224n, {
    id: 0x2c8d54f2314d0f20n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "u8" },
  }],
  [15969366371470605393n, {
    id: 0xdd9e961b0392fc51n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "ResumeKeyBytes",
      fields: [{
        name: "bytes",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0x2c8d54f2314d0f20n, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [15902162861019457979n, {
    id: 0xdcafd4de6b7969bbn,
    type_params: ["T"],
    kind: { tag: "option", element: { tag: "var", name: "T" } },
  }],
  [13439064026636322996n, {
    id: 0xba8125876d6388b4n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "bytes" },
  }],
  [13364648597510457213n, {
    id: 0xb978c5172a88877dn,
    type_params: [],
    kind: {
      tag: "enum",
      name: "MetadataValue",
      variants: [{
        name: "String",
        index: 0,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] } },
      }, {
        name: "Bytes",
        index: 1,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xba8125876d6388b4n, args: [] } },
      }, {
        name: "U64",
        index: 2,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] } },
      }],
    },
  }],
  [11696295240458254911n, {
    id: 0xa251968d339b3a3fn,
    type_params: [],
    kind: {
      tag: "struct",
      name: "MetadataEntry",
      fields: [{ name: "key", type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, {
        name: "value",
        type_ref: { tag: "concrete", type_id: 0xb978c5172a88877dn, args: [] },
        required: true,
      }, { name: "flags", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }, required: true }],
    },
  }],
  [3544357403620257n, {
    id: 0x000c979303fff3a1n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "Hello",
      fields: [{
        name: "parity",
        type_ref: { tag: "concrete", type_id: 0x5b12eb5df7006752n, args: [] },
        required: true,
      }, {
        name: "connection_settings",
        type_ref: { tag: "concrete", type_id: 0x7ea74c54ebb91597n, args: [] },
        required: true,
      }, {
        name: "message_payload_schema",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{
            tag: "concrete",
            type_id: 0x3fb140e3254b4d1dn,
            args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
          }],
        },
        required: true,
      }, {
        name: "supports_retry",
        type_ref: { tag: "concrete", type_id: 0x178367a87f66fb46n, args: [] },
        required: false,
      }, {
        name: "resume_key",
        type_ref: {
          tag: "concrete",
          type_id: 0xdcafd4de6b7969bbn,
          args: [{ tag: "concrete", type_id: 0xdd9e961b0392fc51n, args: [] }],
        },
        required: false,
      }, {
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: false,
      }],
    },
  }],
  [6797402485537510825n, {
    id: 0x5e55398be1d215a9n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "HelloYourself",
      fields: [{
        name: "connection_settings",
        type_ref: { tag: "concrete", type_id: 0x7ea74c54ebb91597n, args: [] },
        required: true,
      }, {
        name: "message_payload_schema",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{
            tag: "concrete",
            type_id: 0x3fb140e3254b4d1dn,
            args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
          }],
        },
        required: true,
      }, {
        name: "supports_retry",
        type_ref: { tag: "concrete", type_id: 0x178367a87f66fb46n, args: [] },
        required: false,
      }, {
        name: "resume_key",
        type_ref: {
          tag: "concrete",
          type_id: 0xdcafd4de6b7969bbn,
          args: [{ tag: "concrete", type_id: 0xdd9e961b0392fc51n, args: [] }],
        },
        required: false,
      }, {
        name: "metadata",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0xa251968d339b3a3fn, args: [] }],
        },
        required: false,
      }],
    },
  }],
  [2739424139120766280n, {
    id: 0x260463bd8d6c6d48n,
    type_params: [],
    kind: { tag: "struct", name: "LetsGo", fields: [] },
  }],
  [13271710879583426775n, {
    id: 0xb82e96ba7b41d8d7n,
    type_params: [],
    kind: {
      tag: "struct",
      name: "Sorry",
      fields: [{
        name: "reason",
        type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] },
        required: true,
      }],
    },
  }],
  [7321830886707858979n, {
    id: 0x659c5e6613b48e23n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "HandshakeMessage",
      variants: [{
        name: "Hello",
        index: 0,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x000c979303fff3a1n, args: [] } },
      }, {
        name: "HelloYourself",
        index: 1,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x5e55398be1d215a9n, args: [] } },
      }, {
        name: "LetsGo",
        index: 2,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0x260463bd8d6c6d48n, args: [] } },
      }, {
        name: "Sorry",
        index: 3,
        payload: { tag: "newtype", type_ref: { tag: "concrete", type_id: 0xb82e96ba7b41d8d7n, args: [] } },
      }],
    },
  }],
]);

export const handshakeMessageRootRef: import("@bearcove/binette").TypeRef = {
  tag: "concrete",
  type_id: 0x659c5e6613b48e23n,
  args: [],
};

export const handshakeMessageSchemas: import("@bearcove/binette").Schema[] = Array.from(
  handshakeMessageSchemaRegistry.values(),
);

export const schemaPayloadSchemaRegistry: import("@bearcove/binette").SchemaRegistry = new Map<
  bigint,
  import("@bearcove/binette").Schema
>([
  [15651524488059042220n, {
    id: 0xd9356298b81639acn,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "u64" },
  }],
  [7889689245711945960n, {
    id: 0x6d7dce914ee150e8n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "string" },
  }],
  [762995119192776039n, {
    id: 0x0a96b404b4d79d67n,
    type_params: ["T"],
    kind: { tag: "list", element: { tag: "var", name: "T" } },
  }],
  [16913039315790463384n, {
    id: 0xeab72fa609e80198n,
    type_params: ["Id"],
    kind: {
      tag: "enum",
      name: "TypeRef",
      variants: [{
        name: "Concrete",
        index: 0,
        payload: {
          tag: "struct",
          fields: [{ name: "type_id", type_ref: { tag: "var", name: "Id" }, required: true }, {
            name: "args",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xeab72fa609e80198n,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "Var",
        index: 1,
        payload: {
          tag: "struct",
          fields: [{
            name: "name",
            type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] },
            required: true,
          }],
        },
      }],
    },
  }],
  [1694311858211060550n, {
    id: 0x178367a87f66fb46n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "bool" },
  }],
  [15084366699922010430n, {
    id: 0xd1566f97da95313en,
    type_params: ["Id"],
    kind: {
      tag: "struct",
      name: "FieldSchema",
      fields: [
        { name: "name", type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] }, required: true },
        {
          name: "type_ref",
          type_ref: {
            tag: "concrete",
            type_id: 0xeab72fa609e80198n,
            args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
          },
          required: true,
        },
        { name: "required", type_ref: { tag: "concrete", type_id: 0x178367a87f66fb46n, args: [] }, required: true },
      ],
    },
  }],
  [2890286099751396276n, {
    id: 0x281c5be4f2ee63b4n,
    type_params: [],
    kind: { tag: "primitive", primitive_type: "u32" },
  }],
  [2581015269456384018n, {
    id: 0x23d19bb677ce9012n,
    type_params: ["Id"],
    kind: {
      tag: "enum",
      name: "VariantPayload",
      variants: [{ name: "Unit", index: 0, payload: { tag: "unit" } }, {
        name: "Newtype",
        index: 1,
        payload: {
          tag: "struct",
          fields: [{
            name: "type_ref",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Tuple",
        index: 2,
        payload: {
          tag: "struct",
          fields: [{
            name: "types",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xeab72fa609e80198n,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "Struct",
        index: 3,
        payload: {
          tag: "struct",
          fields: [{
            name: "fields",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xd1566f97da95313en,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }],
    },
  }],
  [8321007665563425864n, {
    id: 0x737a28629f35dc48n,
    type_params: ["Id"],
    kind: {
      tag: "struct",
      name: "VariantSchema",
      fields: [
        { name: "name", type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] }, required: true },
        { name: "index", type_ref: { tag: "concrete", type_id: 0x281c5be4f2ee63b4n, args: [] }, required: true },
        {
          name: "payload",
          type_ref: {
            tag: "concrete",
            type_id: 0x23d19bb677ce9012n,
            args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
          },
          required: true,
        },
      ],
    },
  }],
  [9922667967649487168n, {
    id: 0x89b465f1abe51940n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "ChannelDirection",
      variants: [{ name: "Tx", index: 0, payload: { tag: "unit" } }, {
        name: "Rx",
        index: 1,
        payload: { tag: "unit" },
      }],
    },
  }],
  [9820435852653867365n, {
    id: 0x8849326088f1b165n,
    type_params: [],
    kind: {
      tag: "enum",
      name: "PrimitiveType",
      variants: [
        { name: "Bool", index: 0, payload: { tag: "unit" } },
        { name: "U8", index: 1, payload: { tag: "unit" } },
        { name: "U16", index: 2, payload: { tag: "unit" } },
        { name: "U32", index: 3, payload: { tag: "unit" } },
        { name: "U64", index: 4, payload: { tag: "unit" } },
        { name: "U128", index: 5, payload: { tag: "unit" } },
        { name: "I8", index: 6, payload: { tag: "unit" } },
        { name: "I16", index: 7, payload: { tag: "unit" } },
        { name: "I32", index: 8, payload: { tag: "unit" } },
        { name: "I64", index: 9, payload: { tag: "unit" } },
        { name: "I128", index: 10, payload: { tag: "unit" } },
        { name: "F32", index: 11, payload: { tag: "unit" } },
        { name: "F64", index: 12, payload: { tag: "unit" } },
        { name: "Char", index: 13, payload: { tag: "unit" } },
        { name: "String", index: 14, payload: { tag: "unit" } },
        { name: "Unit", index: 15, payload: { tag: "unit" } },
        { name: "Never", index: 16, payload: { tag: "unit" } },
        { name: "Bytes", index: 17, payload: { tag: "unit" } },
        { name: "Payload", index: 18, payload: { tag: "unit" } },
      ],
    },
  }],
  [14647032924436458309n, {
    id: 0xcb44b6d76a7c6b45n,
    type_params: ["Id"],
    kind: {
      tag: "enum",
      name: "SchemaKind",
      variants: [{
        name: "Struct",
        index: 0,
        payload: {
          tag: "struct",
          fields: [{
            name: "name",
            type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] },
            required: true,
          }, {
            name: "fields",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xd1566f97da95313en,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "Enum",
        index: 1,
        payload: {
          tag: "struct",
          fields: [{
            name: "name",
            type_ref: { tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] },
            required: true,
          }, {
            name: "variants",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0x737a28629f35dc48n,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "Tuple",
        index: 2,
        payload: {
          tag: "struct",
          fields: [{
            name: "elements",
            type_ref: {
              tag: "concrete",
              type_id: 0x0a96b404b4d79d67n,
              args: [{
                tag: "concrete",
                type_id: 0xeab72fa609e80198n,
                args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
              }],
            },
            required: true,
          }],
        },
      }, {
        name: "List",
        index: 3,
        payload: {
          tag: "struct",
          fields: [{
            name: "element",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Map",
        index: 4,
        payload: {
          tag: "struct",
          fields: [{
            name: "key",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }, {
            name: "value",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Array",
        index: 5,
        payload: {
          tag: "struct",
          fields: [{
            name: "element",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }, { name: "length", type_ref: { tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }, required: true }],
        },
      }, {
        name: "Option",
        index: 6,
        payload: {
          tag: "struct",
          fields: [{
            name: "element",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Channel",
        index: 7,
        payload: {
          tag: "struct",
          fields: [{
            name: "direction",
            type_ref: { tag: "concrete", type_id: 0x89b465f1abe51940n, args: [] },
            required: true,
          }, {
            name: "element",
            type_ref: {
              tag: "concrete",
              type_id: 0xeab72fa609e80198n,
              args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
            },
            required: true,
          }],
        },
      }, {
        name: "Primitive",
        index: 8,
        payload: {
          tag: "struct",
          fields: [{
            name: "primitive_type",
            type_ref: { tag: "concrete", type_id: 0x8849326088f1b165n, args: [] },
            required: true,
          }],
        },
      }],
    },
  }],
  [4589520839594691869n, {
    id: 0x3fb140e3254b4d1dn,
    type_params: ["Id"],
    kind: {
      tag: "struct",
      name: "Schema",
      fields: [{ name: "id", type_ref: { tag: "var", name: "Id" }, required: true }, {
        name: "type_params",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{ tag: "concrete", type_id: 0x6d7dce914ee150e8n, args: [] }],
        },
        required: false,
      }, {
        name: "kind",
        type_ref: {
          tag: "concrete",
          type_id: 0xcb44b6d76a7c6b45n,
          args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
        },
        required: true,
      }],
    },
  }],
  [11549819475048554364n, {
    id: 0xa049339e76285f7cn,
    type_params: [],
    kind: {
      tag: "struct",
      name: "SchemaPayload",
      fields: [{
        name: "schemas",
        type_ref: {
          tag: "concrete",
          type_id: 0x0a96b404b4d79d67n,
          args: [{
            tag: "concrete",
            type_id: 0x3fb140e3254b4d1dn,
            args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
          }],
        },
        required: true,
      }, {
        name: "root",
        type_ref: {
          tag: "concrete",
          type_id: 0xeab72fa609e80198n,
          args: [{ tag: "concrete", type_id: 0xd9356298b81639acn, args: [] }],
        },
        required: true,
      }],
    },
  }],
]);

export const schemaPayloadRootRef: import("@bearcove/binette").TypeRef = {
  tag: "concrete",
  type_id: 0xa049339e76285f7cn,
  args: [],
};

export const schemaPayloadSchemas: import("@bearcove/binette").Schema[] = Array.from(
  schemaPayloadSchemaRegistry.values(),
);
