// @generated by vox-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --swift`

import BinetteSwiftProbes
import CBinette
import VoxSwift

// Named value types
public enum SwiftOutcome {
    case accepted(String)
    case rejected(UInt32)
}

public struct SwiftCall {
    public var method: UInt32
    public var nonce: UInt64
    public var ratio: Double
    public var title: String
    public var payload: [UInt8]
    public var retry: UInt16?
    public var outcome: SwiftOutcome
    public var output: VoxSwiftChannel
    public init(method: UInt32, nonce: UInt64, ratio: Double, title: String, payload: [UInt8], retry: UInt16?, outcome: SwiftOutcome, output: VoxSwiftChannel) {
        self.method = method
        self.nonce = nonce
        self.ratio = ratio
        self.title = title
        self.payload = payload
        self.retry = retry
        self.outcome = outcome
        self.output = output
    }
}

public struct SwiftReply {
    public var message: String
    public var retry: UInt16?
    public init(message: String, retry: UInt16?) {
        self.message = message
        self.retry = retry
    }
}

// Method argument tuple carriers
public struct SwiftCanarySubmitArgs {
    public var call: SwiftCall
    public init(call: SwiftCall) {
        self.call = call
    }
}

// Local binette descriptors
private func descriptorForString(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.string()
}

private func descriptorForUInt32(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_u32_type_id(), UInt32.self)
}

private func descriptorForSwiftOutcome(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.enumeration(
        typeID: 0xBD1A7E6B99D5C321,
        layout: binetteLayout(of: SwiftOutcome.self),
        tag: BinetteLocalEnumTagAccessAbi(
            tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
            direct_offset: 0,
            thunk: BinetteLocalEnumTagThunkAbi(call: swiftOutcomeTag, context: nil)
        ),
        variants: [
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Accepted"),
                index: 0,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftOutcomeProjectAcceptedBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftOutcomeProjectAcceptedInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftOutcomeDropAcceptedProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftOutcomeConstructAccepted,
                    context: nil
                ),
                payload: descriptorForString(in: arena)
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Rejected"),
                index: 1,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftOutcomeProjectRejectedBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftOutcomeProjectRejectedInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftOutcomeDropRejectedProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftOutcomeConstructRejected,
                    context: nil
                ),
                payload: descriptorForUInt32(in: arena)
            ),
        ]
    )
}

private func swiftOutcomeTag(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UInt32 {
    switch UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).pointee {
    case .accepted(_): return 0
    case .rejected(_): return 1
    }
}

private func swiftOutcomeProjectAcceptedBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func swiftOutcomeProjectAcceptedInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<String>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).pointee
    guard case let .accepted(payload) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: String.self).initialize(to: payload)
    return true
}

private func swiftOutcomeDropAcceptedProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: String.self).deinitialize(count: 1)
}

private func swiftOutcomeConstructAccepted(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    let bytes = UnsafeBufferPointer(start: payloadBytes, count: payloadLen)
    guard let payloadValue = String(bytes: bytes, encoding: .utf8) else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).initialize(to: .accepted(payloadValue))
    return true
}

private func swiftOutcomeProjectRejectedBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func swiftOutcomeProjectRejectedInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<UInt32>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).pointee
    guard case let .rejected(payload) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: UInt32.self).initialize(to: payload)
    return true
}

private func swiftOutcomeDropRejectedProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: UInt32.self).deinitialize(count: 1)
}

private func swiftOutcomeConstructRejected(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == MemoryLayout<UInt32>.size else { return false }
    var payloadValue: UInt32 = 0
    withUnsafeMutableBytes(of: &payloadValue) { out in
        out.copyMemory(from: UnsafeRawBufferPointer(start: payloadBytes, count: payloadLen))
    }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).initialize(to: .rejected(payloadValue))
    return true
}

private func descriptorForUInt64(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_u64_type_id(), UInt64.self)
}

private func descriptorForDouble(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_f64_type_id(), Double.self)
}

private func descriptorForBytes(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.bytes()
}

private func descriptorForUInt16(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_u16_type_id(), UInt16.self)
}

private func descriptorForOptionalUInt16(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    let some = descriptorForUInt16(in: arena)
    return arena.option(
        typeID: 0x4C0CA7E5DEEA765C,
        layout: binetteLayout(of: UInt16?.self),
        some: some,
        representation: binetteDirectOptionalU16Representation()
    )
}

private func descriptorForTxUInt32(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.externalAttachment(
        typeID: 0x2B3676C06C6D15CC,
        kind: "vox.channel",
        layout: binetteLayout(of: VoxSwiftChannel.self),
        metadataFields: [
            arena.externalMetadataField(
                "direction",
                arena.externalMetadataString("tx")
            ),
            arena.externalMetadataField(
                "element",
                arena.externalMetadataTypeRef(descriptorForUInt32(in: arena))
            ),
        ]
    )
}

private func descriptorForSwiftCall(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0x71DEEEBE3F6007F5,
        layout: binetteLayout(of: SwiftCall.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("method"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.method)!,
                descriptor: descriptorForUInt32(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("nonce"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.nonce)!,
                descriptor: descriptorForUInt64(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("ratio"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.ratio)!,
                descriptor: descriptorForDouble(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("title"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.title)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("payload"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.payload)!,
                descriptor: descriptorForBytes(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("retry"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.retry)!,
                descriptor: descriptorForOptionalUInt16(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("outcome"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.outcome)!,
                descriptor: descriptorForSwiftOutcome(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("output"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.output)!,
                descriptor: descriptorForTxUInt32(in: arena)
            ),
        ]
    )
}

private func descriptorForSwiftReply(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0xF57906185187E9B8,
        layout: binetteLayout(of: SwiftReply.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("message"),
                offset: MemoryLayout<SwiftReply>.offset(of: \SwiftReply.message)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("retry"),
                offset: MemoryLayout<SwiftReply>.offset(of: \SwiftReply.retry)!,
                descriptor: descriptorForOptionalUInt16(in: arena)
            ),
        ]
    )
}

private func descriptorForSwiftCanarySubmitArgs(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.tuple(
        typeID: 0xC0E67915325F479C,
        layout: binetteLayout(of: SwiftCanarySubmitArgs.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("0"),
                offset: MemoryLayout<SwiftCanarySubmitArgs>.offset(of: \SwiftCanarySubmitArgs.call)!,
                descriptor: descriptorForSwiftCall(in: arena)
            ),
        ]
    )
}

// Method codecs
public final class SwiftCanaryMethodCodecs {
    private let arena = BinetteCAbiDescriptorArena()

    public init() {}

    public func submit() throws -> VoxSwiftMethodCodec {
        try VoxSwiftMethodCodec(
            argsDescriptor: descriptorForSwiftCanarySubmitArgs(in: arena),
            responseDescriptor: descriptorForSwiftReply(in: arena)
        )
    }

}
