// @generated by vox-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --swift`

import BinetteSwiftProbes
import CBinette
import VoxSwift

// Vox response wire carrier types
public enum SwiftCanaryVoxErrorNever {
    case user(Void)
    case unknownMethod
    case invalidPayload(String)
    case cancelled
    case connectionClosed
    case sessionShutdown
    case sendFailed
    case indeterminate
}

public enum SwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever {
    case ok(SwiftReply)
    case err(SwiftCanaryVoxErrorNever)
}

// Named value types
public struct SwiftPoint {
    public var x: Int32
    public var y: Int32
    public init(x: Int32, y: Int32) {
        self.x = x
        self.y = y
    }
}

public enum SwiftShape {
    case circle(radius: Double)
    case rectangle(width: Double, height: Double)
    case point
}

public enum SwiftOutcome {
    case accepted(String)
    case rejected(UInt32)
}

public struct SwiftCall {
    public var method: UInt32
    public var nonce: UInt64
    public var ratio: Double
    public var title: String
    public var note: String?
    public var payload: [UInt8]
    public var points: [SwiftPoint]
    public var shape: SwiftShape
    public var retry: UInt16?
    public var outcome: SwiftOutcome
    public var output: VoxSwiftChannel
    public init(method: UInt32, nonce: UInt64, ratio: Double, title: String, note: String?, payload: [UInt8], points: [SwiftPoint], shape: SwiftShape, retry: UInt16?, outcome: SwiftOutcome, output: VoxSwiftChannel) {
        self.method = method
        self.nonce = nonce
        self.ratio = ratio
        self.title = title
        self.note = note
        self.payload = payload
        self.points = points
        self.shape = shape
        self.retry = retry
        self.outcome = outcome
        self.output = output
    }
}

public struct SwiftReply {
    public var message: String
    public var retry: UInt16?
    public init(message: String, retry: UInt16?) {
        self.message = message
        self.retry = retry
    }
}

// Enum payload carriers
private struct SwiftShapeCirclePayload {
    var radius: Double
}

private struct SwiftShapeRectanglePayload {
    var width: Double
    var height: Double
}


// Method argument tuple carriers
public struct SwiftCanarySubmitArgs {
    public var call: SwiftCall
    public init(call: SwiftCall) {
        self.call = call
    }
}

// Local binette descriptors
private func descriptorForInt32(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_i32_type_id(), Int32.self)
}

private func descriptorForSwiftPoint(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0xB8317D83A0D61B5B,
        layout: binetteLayout(of: SwiftPoint.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("x"),
                offset: MemoryLayout<SwiftPoint>.offset(of: \SwiftPoint.x)!,
                descriptor: descriptorForInt32(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("y"),
                offset: MemoryLayout<SwiftPoint>.offset(of: \SwiftPoint.y)!,
                descriptor: descriptorForInt32(in: arena)
            ),
        ]
    )
}

private func descriptorForDouble(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_f64_type_id(), Double.self)
}

private func descriptorForSwiftShapeCirclePayload(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0x196C7ACF76FFE754,
        layout: binetteLayout(of: SwiftShapeCirclePayload.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("radius"),
                offset: MemoryLayout<SwiftShapeCirclePayload>.offset(of: \SwiftShapeCirclePayload.radius)!,
                descriptor: descriptorForDouble(in: arena)
            ),
        ]
    )
}

private func descriptorForSwiftShapeRectanglePayload(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0x196C7ACF76FFE7D4,
        layout: binetteLayout(of: SwiftShapeRectanglePayload.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("width"),
                offset: MemoryLayout<SwiftShapeRectanglePayload>.offset(of: \SwiftShapeRectanglePayload.width)!,
                descriptor: descriptorForDouble(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("height"),
                offset: MemoryLayout<SwiftShapeRectanglePayload>.offset(of: \SwiftShapeRectanglePayload.height)!,
                descriptor: descriptorForDouble(in: arena)
            ),
        ]
    )
}

private func descriptorForSwiftShape(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.enumeration(
        typeID: 0x266C7ACF76FFE719,
        layout: binetteLayout(of: SwiftShape.self),
        tag: BinetteLocalEnumTagAccessAbi(
            tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
            direct_offset: 0,
            thunk: BinetteLocalEnumTagThunkAbi(call: swiftShapeTag, context: nil)
        ),
        variants: [
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Circle"),
                index: 0,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftShapeProjectCircleBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftShapeProjectCircleInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftShapeDropCircleProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftShapeConstructCircle,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_STRUCT),
                payload: descriptorForSwiftShapeCirclePayload(in: arena)
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Rectangle"),
                index: 1,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftShapeProjectRectangleBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftShapeProjectRectangleInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftShapeDropRectangleProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftShapeConstructRectangle,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_STRUCT),
                payload: descriptorForSwiftShapeRectanglePayload(in: arena)
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Point"),
                index: 2,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftShapeProjectPointBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftShapeProjectPointInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftShapeDropPointProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftShapeConstructPoint,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_UNIT),
                payload: nil
            ),
        ]
    )
}

private func swiftShapeTag(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UInt32 {
    switch UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftShape.self).pointee {
    case .circle(_): return 0
    case .rectangle(_, _): return 1
    case .point: return 2
    }
}

private func swiftShapeProjectCircleBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func swiftShapeProjectCircleInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<SwiftShapeCirclePayload>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftShape.self).pointee
    guard case let .circle(radius) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: SwiftShapeCirclePayload.self).initialize(to: SwiftShapeCirclePayload(radius: radius))
    return true
}

private func swiftShapeDropCircleProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftShapeCirclePayload.self).deinitialize(count: 1)
}

private func swiftShapeConstructCircle(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == MemoryLayout<SwiftShapeCirclePayload>.size else { return false }
    let payloadValue = UnsafeRawPointer(payloadBytes!).assumingMemoryBound(to: SwiftShapeCirclePayload.self).pointee
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftShape.self).initialize(to: .circle(radius: payloadValue.radius))
    return true
}

private func swiftShapeProjectRectangleBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func swiftShapeProjectRectangleInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<SwiftShapeRectanglePayload>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftShape.self).pointee
    guard case let .rectangle(width, height) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: SwiftShapeRectanglePayload.self).initialize(to: SwiftShapeRectanglePayload(width: width, height: height))
    return true
}

private func swiftShapeDropRectangleProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftShapeRectanglePayload.self).deinitialize(count: 1)
}

private func swiftShapeConstructRectangle(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == MemoryLayout<SwiftShapeRectanglePayload>.size else { return false }
    let payloadValue = UnsafeRawPointer(payloadBytes!).assumingMemoryBound(to: SwiftShapeRectanglePayload.self).pointee
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftShape.self).initialize(to: .rectangle(width: payloadValue.width, height: payloadValue.height))
    return true
}

private func swiftShapeProjectPointBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func swiftShapeProjectPointInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func swiftShapeDropPointProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func swiftShapeConstructPoint(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftShape.self).initialize(to: .point)
    return true
}

private func descriptorForString(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.string()
}

private func descriptorForUInt32(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_u32_type_id(), UInt32.self)
}

private func descriptorForSwiftOutcome(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.enumeration(
        typeID: 0xBD1A7E6B99D5C321,
        layout: binetteLayout(of: SwiftOutcome.self),
        tag: BinetteLocalEnumTagAccessAbi(
            tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
            direct_offset: 0,
            thunk: BinetteLocalEnumTagThunkAbi(call: swiftOutcomeTag, context: nil)
        ),
        variants: [
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Accepted"),
                index: 0,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftOutcomeProjectAcceptedBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftOutcomeProjectAcceptedInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftOutcomeDropAcceptedProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftOutcomeConstructAccepted,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_NEWTYPE),
                payload: descriptorForString(in: arena)
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Rejected"),
                index: 1,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftOutcomeProjectRejectedBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftOutcomeProjectRejectedInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftOutcomeDropRejectedProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftOutcomeConstructRejected,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_NEWTYPE),
                payload: descriptorForUInt32(in: arena)
            ),
        ]
    )
}

private func swiftOutcomeTag(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UInt32 {
    switch UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).pointee {
    case .accepted(_): return 0
    case .rejected(_): return 1
    }
}

private func swiftOutcomeProjectAcceptedBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func swiftOutcomeProjectAcceptedInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<String>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).pointee
    guard case let .accepted(payload) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: String.self).initialize(to: payload)
    return true
}

private func swiftOutcomeDropAcceptedProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: String.self).deinitialize(count: 1)
}

private func swiftOutcomeConstructAccepted(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    let bytes = UnsafeBufferPointer(start: payloadBytes, count: payloadLen)
    guard let payloadValue = String(bytes: bytes, encoding: .utf8) else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).initialize(to: .accepted(payloadValue))
    return true
}

private func swiftOutcomeProjectRejectedBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func swiftOutcomeProjectRejectedInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<UInt32>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).pointee
    guard case let .rejected(payload) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: UInt32.self).initialize(to: payload)
    return true
}

private func swiftOutcomeDropRejectedProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: UInt32.self).deinitialize(count: 1)
}

private func swiftOutcomeConstructRejected(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == MemoryLayout<UInt32>.size else { return false }
    var payloadValue: UInt32 = 0
    withUnsafeMutableBytes(of: &payloadValue) { out in
        out.copyMemory(from: UnsafeRawBufferPointer(start: payloadBytes, count: payloadLen))
    }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftOutcome.self).initialize(to: .rejected(payloadValue))
    return true
}

private func descriptorForUInt64(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_u64_type_id(), UInt64.self)
}

private func descriptorForOptionalString(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    let some = descriptorForString(in: arena)
    return arena.option(
        typeID: 0x3A97A1A4F2558EC2,
        layout: binetteLayout(of: String?.self),
        some: some,
        representation: binetteThunkOptionalStringRepresentation()
    )
}

private func descriptorForBytes(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.bytes()
}

private func descriptorForArrayOfSwiftPoint(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    let element = descriptorForSwiftPoint(in: arena)
    return arena.sequence(
        typeID: 0x6F6B7FD9CB188054,
        layout: binetteLayout(of: [SwiftPoint].self),
        element: element,
        storage: binetteThunkSequenceStorage(
            elementStride: MemoryLayout<SwiftPoint>.stride,
            len: arrayOfSwiftPointLen,
            elementProjectInto: arrayOfSwiftPointProjectElementInto,
            elementDropProjected: arrayOfSwiftPointDropProjectedElement,
            writeFixedElements: arrayOfSwiftPointWriteFixedElements
        )
    )
}

private func arrayOfSwiftPointLen(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> Int {
    UnsafeRawPointer(value!).assumingMemoryBound(to: [SwiftPoint].self).pointee.count
}

private func arrayOfSwiftPointProjectElementInto(_ value: UnsafePointer<UInt8>?, _ index: Int, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    let values = UnsafeRawPointer(value!).assumingMemoryBound(to: [SwiftPoint].self).pointee
    guard index >= 0, index < values.count, outLen == MemoryLayout<SwiftPoint>.size else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: SwiftPoint.self).initialize(to: values[index])
    return true
}

private func arrayOfSwiftPointDropProjectedElement(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftPoint.self).deinitialize(count: 1)
}

private func arrayOfSwiftPointWriteFixedElements(_ value: UnsafeMutablePointer<UInt8>?, _ ptr: UnsafePointer<UInt8>?, _ count: Int, _ elementStride: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard elementStride == MemoryLayout<SwiftPoint>.stride else { return false }
    var values: [SwiftPoint] = []
    values.reserveCapacity(count)
    for index in 0..<count {
        let elementPointer = UnsafeMutablePointer<SwiftPoint>.allocate(capacity: 1)
        let source = UnsafeRawPointer(ptr!).advanced(by: index * elementStride)
        UnsafeMutableRawPointer(elementPointer).copyMemory(from: source, byteCount: MemoryLayout<SwiftPoint>.size)
        values.append(elementPointer.move())
        elementPointer.deallocate()
    }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: [SwiftPoint].self).initialize(to: values)
    return true
}

private func descriptorForUInt16(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_u16_type_id(), UInt16.self)
}

private func descriptorForOptionalUInt16(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    let some = descriptorForUInt16(in: arena)
    return arena.option(
        typeID: 0x4C0CA7E5DEEA765C,
        layout: binetteLayout(of: UInt16?.self),
        some: some,
        representation: binetteDirectOptionalU16Representation()
    )
}

private func descriptorForTxUInt32(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.externalAttachment(
        typeID: 0x2B3676C06C6D15CC,
        kind: "vox.channel",
        layout: binetteLayout(of: VoxSwiftChannel.self),
        metadataFields: [
            arena.externalMetadataField(
                "direction",
                arena.externalMetadataString("tx")
            ),
            arena.externalMetadataField(
                "element",
                arena.externalMetadataTypeRef(descriptorForUInt32(in: arena))
            ),
        ]
    )
}

private func descriptorForSwiftCall(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0xAA5BA057E517113A,
        layout: binetteLayout(of: SwiftCall.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("method"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.method)!,
                descriptor: descriptorForUInt32(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("nonce"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.nonce)!,
                descriptor: descriptorForUInt64(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("ratio"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.ratio)!,
                descriptor: descriptorForDouble(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("title"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.title)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("note"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.note)!,
                descriptor: descriptorForOptionalString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("payload"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.payload)!,
                descriptor: descriptorForBytes(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("points"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.points)!,
                descriptor: descriptorForArrayOfSwiftPoint(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("shape"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.shape)!,
                descriptor: descriptorForSwiftShape(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("retry"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.retry)!,
                descriptor: descriptorForOptionalUInt16(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("outcome"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.outcome)!,
                descriptor: descriptorForSwiftOutcome(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("output"),
                offset: MemoryLayout<SwiftCall>.offset(of: \SwiftCall.output)!,
                descriptor: descriptorForTxUInt32(in: arena)
            ),
        ]
    )
}

private func descriptorForSwiftReply(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0xF57906185187E9B8,
        layout: binetteLayout(of: SwiftReply.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("message"),
                offset: MemoryLayout<SwiftReply>.offset(of: \SwiftReply.message)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("retry"),
                offset: MemoryLayout<SwiftReply>.offset(of: \SwiftReply.retry)!,
                descriptor: descriptorForOptionalUInt16(in: arena)
            ),
        ]
    )
}

private func descriptorForSwiftCanarySubmitArgs(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.tuple(
        typeID: 0xC0E67915325F479C,
        layout: binetteLayout(of: SwiftCanarySubmitArgs.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("0"),
                offset: MemoryLayout<SwiftCanarySubmitArgs>.offset(of: \SwiftCanarySubmitArgs.call)!,
                descriptor: descriptorForSwiftCall(in: arena)
            ),
        ]
    )
}

private func descriptorForVoid(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_unit_type_id(), Void.self)
}

private func descriptorForSwiftCanaryVoxErrorNever(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.enumeration(
        typeID: 0x4CF4B2AEB98A1939,
        layout: binetteLayout(of: SwiftCanaryVoxErrorNever.self),
        tag: BinetteLocalEnumTagAccessAbi(
            tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
            direct_offset: 0,
            thunk: BinetteLocalEnumTagThunkAbi(call: swiftCanaryVoxErrorNeverTag, context: nil)
        ),
        variants: [
            BinetteLocalVariantAbi(
                name: binetteLocalStr("User"),
                index: 0,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxErrorNeverProjectUserBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxErrorNeverProjectUserInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxErrorNeverDropUserProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxErrorNeverConstructUser,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_NEWTYPE),
                payload: descriptorForVoid(in: arena)
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("UnknownMethod"),
                index: 1,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxErrorNeverProjectUnknownMethodBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxErrorNeverProjectUnknownMethodInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxErrorNeverDropUnknownMethodProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxErrorNeverConstructUnknownMethod,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_UNIT),
                payload: nil
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("InvalidPayload"),
                index: 2,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxErrorNeverProjectInvalidPayloadBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxErrorNeverProjectInvalidPayloadInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxErrorNeverDropInvalidPayloadProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxErrorNeverConstructInvalidPayload,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_NEWTYPE),
                payload: descriptorForString(in: arena)
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Cancelled"),
                index: 3,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxErrorNeverProjectCancelledBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxErrorNeverProjectCancelledInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxErrorNeverDropCancelledProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxErrorNeverConstructCancelled,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_UNIT),
                payload: nil
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("ConnectionClosed"),
                index: 4,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxErrorNeverProjectConnectionClosedBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxErrorNeverProjectConnectionClosedInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxErrorNeverDropConnectionClosedProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxErrorNeverConstructConnectionClosed,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_UNIT),
                payload: nil
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("SessionShutdown"),
                index: 5,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxErrorNeverProjectSessionShutdownBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxErrorNeverProjectSessionShutdownInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxErrorNeverDropSessionShutdownProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxErrorNeverConstructSessionShutdown,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_UNIT),
                payload: nil
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("SendFailed"),
                index: 6,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxErrorNeverProjectSendFailedBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxErrorNeverProjectSendFailedInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxErrorNeverDropSendFailedProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxErrorNeverConstructSendFailed,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_UNIT),
                payload: nil
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Indeterminate"),
                index: 7,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxErrorNeverProjectIndeterminateBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxErrorNeverProjectIndeterminateInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxErrorNeverDropIndeterminateProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxErrorNeverConstructIndeterminate,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_UNIT),
                payload: nil
            ),
        ]
    )
}

private func swiftCanaryVoxErrorNeverTag(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UInt32 {
    switch UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).pointee {
    case .user: return 0
    case .unknownMethod: return 1
    case .invalidPayload: return 2
    case .cancelled: return 3
    case .connectionClosed: return 4
    case .sessionShutdown: return 5
    case .sendFailed: return 6
    case .indeterminate: return 7
    }
}

private func swiftCanaryVoxErrorNeverProjectUserBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxErrorNeverProjectUnknownMethodBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxErrorNeverProjectInvalidPayloadBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxErrorNeverProjectCancelledBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxErrorNeverProjectConnectionClosedBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxErrorNeverProjectSessionShutdownBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxErrorNeverProjectSendFailedBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxErrorNeverProjectIndeterminateBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxErrorNeverProjectUserInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<Void>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).pointee
    guard case let .user(payload) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: Void.self).initialize(to: payload)
    return true
}

private func swiftCanaryVoxErrorNeverDropUserProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: Void.self).deinitialize(count: 1)
}

private func swiftCanaryVoxErrorNeverConstructUser(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == MemoryLayout<Void>.size else { return false }
    let payloadValue: Void = ()
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: .user(payloadValue))
    return true
}

private func swiftCanaryVoxErrorNeverProjectUnknownMethodInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func swiftCanaryVoxErrorNeverDropUnknownMethodProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func swiftCanaryVoxErrorNeverConstructUnknownMethod(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: .unknownMethod)
    return true
}

private func swiftCanaryVoxErrorNeverProjectInvalidPayloadInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<String>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).pointee
    guard case let .invalidPayload(payload) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: String.self).initialize(to: payload)
    return true
}

private func swiftCanaryVoxErrorNeverDropInvalidPayloadProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: String.self).deinitialize(count: 1)
}

private func swiftCanaryVoxErrorNeverConstructInvalidPayload(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    let bytes = UnsafeBufferPointer(start: payloadBytes, count: payloadLen)
    guard let payloadValue = String(bytes: bytes, encoding: .utf8) else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: .invalidPayload(payloadValue))
    return true
}

private func swiftCanaryVoxErrorNeverProjectCancelledInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func swiftCanaryVoxErrorNeverDropCancelledProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func swiftCanaryVoxErrorNeverConstructCancelled(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: .cancelled)
    return true
}

private func swiftCanaryVoxErrorNeverProjectConnectionClosedInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func swiftCanaryVoxErrorNeverDropConnectionClosedProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func swiftCanaryVoxErrorNeverConstructConnectionClosed(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: .connectionClosed)
    return true
}

private func swiftCanaryVoxErrorNeverProjectSessionShutdownInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func swiftCanaryVoxErrorNeverDropSessionShutdownProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func swiftCanaryVoxErrorNeverConstructSessionShutdown(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: .sessionShutdown)
    return true
}

private func swiftCanaryVoxErrorNeverProjectSendFailedInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func swiftCanaryVoxErrorNeverDropSendFailedProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func swiftCanaryVoxErrorNeverConstructSendFailed(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: .sendFailed)
    return true
}

private func swiftCanaryVoxErrorNeverProjectIndeterminateInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func swiftCanaryVoxErrorNeverDropIndeterminateProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func swiftCanaryVoxErrorNeverConstructIndeterminate(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: .indeterminate)
    return true
}

private func descriptorForSwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.enumeration(
        typeID: 0x42046DE663BEEEF0,
        layout: binetteLayout(of: SwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever.self),
        tag: BinetteLocalEnumTagAccessAbi(
            tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
            direct_offset: 0,
            thunk: BinetteLocalEnumTagThunkAbi(call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverTag, context: nil)
        ),
        variants: [
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Ok"),
                index: 0,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverProjectOkBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverProjectOkInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverDropOkProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverConstructOk,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_NEWTYPE),
                payload: descriptorForSwiftReply(in: arena)
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Err"),
                index: 1,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverProjectErrBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverProjectErrInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverDropErrProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverConstructErr,
                    context: nil
                ),
                payload_kind: UInt32(BINETTE_LOCAL_VARIANT_PAYLOAD_NEWTYPE),
                payload: descriptorForSwiftCanaryVoxErrorNever(in: arena)
            ),
        ]
    )
}

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverTag(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UInt32 {
    switch UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever.self).pointee {
    case .ok: return 0
    case .err: return 1
    }
}

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverProjectOkBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverProjectErrBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? { nil }

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverProjectOkInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<SwiftReply>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever.self).pointee
    guard case let .ok(payload) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: SwiftReply.self).initialize(to: payload)
    return true
}

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverDropOkProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftReply.self).deinitialize(count: 1)
}

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverConstructOk(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == MemoryLayout<SwiftReply>.size else { return false }
    let payloadPointer = UnsafeMutableRawPointer(mutating: payloadBytes!).assumingMemoryBound(to: SwiftReply.self)
    let payloadValue = payloadPointer.pointee
    payloadPointer.deinitialize(count: 1)
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever.self).initialize(to: .ok(payloadValue))
    return true
}

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverProjectErrInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard outLen == MemoryLayout<SwiftCanaryVoxErrorNever>.size else { return false }
    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever.self).pointee
    guard case let .err(payload) = value else { return false }
    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).initialize(to: payload)
    return true
}

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverDropErrProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self).deinitialize(count: 1)
}

private func swiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNeverConstructErr(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == MemoryLayout<SwiftCanaryVoxErrorNever>.size else { return false }
    let payloadPointer = UnsafeMutableRawPointer(mutating: payloadBytes!).assumingMemoryBound(to: SwiftCanaryVoxErrorNever.self)
    let payloadValue = payloadPointer.pointee
    payloadPointer.deinitialize(count: 1)
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: SwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever.self).initialize(to: .err(payloadValue))
    return true
}

// Method codecs
public final class SwiftCanaryMethodCodecs {
    private let arena = BinetteCAbiDescriptorArena()

    public init() {}

    public func submit() throws -> VoxSwiftMethodCodec {
        try VoxSwiftMethodCodec(
            methodId: 0x61FA9915325F479C,
            argsDescriptor: descriptorForSwiftCanarySubmitArgs(in: arena),
            responseDescriptor: descriptorForSwiftReply(in: arena),
            responseWireDescriptor: descriptorForSwiftCanaryVoxResultSwiftReplySwiftCanaryVoxErrorNever(in: arena)
        )
    }

}
