// @generated by vox-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --swift`

import BinetteSwiftProbes
import CBinette
import VoxSwift

// Named value types
public struct Profile {
    public var name: String
    public var bio: String
    public var avatar: String?
    public init(name: String, bio: String, avatar: String?) {
        self.name = name
        self.bio = bio
        self.avatar = avatar
    }
}

public struct Record {
    public var gamma: Double
    public var alpha: Int32
    public var beta: String
    public init(gamma: Double, alpha: Int32, beta: String) {
        self.gamma = gamma
        self.alpha = alpha
        self.beta = beta
    }
}

public enum Status {
    case active
    case inactive
    case suspended
}

public struct Tag {
    public var label: String
    public var priority: UInt32
    public init(label: String, priority: UInt32) {
        self.label = label
        self.priority = priority
    }
}

public struct Measurement {
    public var unit: String
    public var value: String
    public init(unit: String, value: String) {
        self.unit = unit
        self.value = value
    }
}

public struct Config {
    public var key: String
    public var value: String
    public var owner: String
    public init(key: String, value: String, owner: String) {
        self.key = key
        self.value = value
        self.owner = owner
    }
}

// Method argument tuple carriers
public struct TestbedEchoProfileArgs {
    public var profile: Profile
    public init(profile: Profile) {
        self.profile = profile
    }
}

public struct TestbedEchoRecordArgs {
    public var record: Record
    public init(record: Record) {
        self.record = record
    }
}

public struct TestbedEchoStatusArgs {
    public var status: Status
    public init(status: Status) {
        self.status = status
    }
}

public struct TestbedEchoTagArgs {
    public var tag: Tag
    public init(tag: Tag) {
        self.tag = tag
    }
}

public struct TestbedEchoMeasurementArgs {
    public var m: Measurement
    public init(m: Measurement) {
        self.m = m
    }
}

public struct TestbedEchoConfigArgs {
    public var c: Config
    public init(c: Config) {
        self.c = c
    }
}

// Local binette descriptors
private func descriptorForString(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.string()
}

private func descriptorForOptionalString(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    let some = descriptorForString(in: arena)
    return arena.option(
        typeID: 0x3A97A1A4F2558EC2,
        layout: binetteLayout(of: String?.self),
        some: some,
        representation: binetteThunkOptionalStringRepresentation()
    )
}

private func descriptorForProfile(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0xA44004E457AC50DC,
        layout: binetteLayout(of: Profile.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("name"),
                offset: MemoryLayout<Profile>.offset(of: \Profile.name)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("bio"),
                offset: MemoryLayout<Profile>.offset(of: \Profile.bio)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("avatar"),
                offset: MemoryLayout<Profile>.offset(of: \Profile.avatar)!,
                descriptor: descriptorForOptionalString(in: arena)
            ),
        ]
    )
}

private func descriptorForDouble(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_f64_type_id(), Double.self)
}

private func descriptorForInt32(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_i32_type_id(), Int32.self)
}

private func descriptorForRecord(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0x192310B3D2EDCBBB,
        layout: binetteLayout(of: Record.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("gamma"),
                offset: MemoryLayout<Record>.offset(of: \Record.gamma)!,
                descriptor: descriptorForDouble(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("alpha"),
                offset: MemoryLayout<Record>.offset(of: \Record.alpha)!,
                descriptor: descriptorForInt32(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("beta"),
                offset: MemoryLayout<Record>.offset(of: \Record.beta)!,
                descriptor: descriptorForString(in: arena)
            ),
        ]
    )
}

private func descriptorForStatus(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.enumeration(
        typeID: 0x2F0FF266DDE23386,
        layout: binetteLayout(of: Status.self),
        tag: BinetteLocalEnumTagAccessAbi(
            tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
            direct_offset: 0,
            thunk: BinetteLocalEnumTagThunkAbi(call: statusTag, context: nil)
        ),
        variants: [
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Active"),
                index: 0,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: statusProjectActiveBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: statusProjectActiveInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: statusDropActiveProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: statusConstructActive,
                    context: nil
                ),
                payload: nil
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Inactive"),
                index: 1,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: statusProjectInactiveBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: statusProjectInactiveInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: statusDropInactiveProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: statusConstructInactive,
                    context: nil
                ),
                payload: nil
            ),
            BinetteLocalVariantAbi(
                name: binetteLocalStr("Suspended"),
                index: 2,
                project: BinetteLocalVariantProjectAccessAbi(
                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),
                    direct_offset: 0,
                    thunk: BinetteLocalVariantProjectThunkAbi(call: statusProjectSuspendedBorrowed, context: nil)
                ),
                project_into: BinetteLocalVariantProjectIntoAbi(
                    call: statusProjectSuspendedInto,
                    context: nil
                ),
                drop_projected: BinetteLocalVariantDropAbi(
                    call: statusDropSuspendedProjected,
                    context: nil
                ),
                construct: BinetteLocalVariantConstructAbi(
                    call: statusConstructSuspended,
                    context: nil
                ),
                payload: nil
            ),
        ]
    )
}

private func statusTag(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UInt32 {
    switch UnsafeRawPointer(value!).assumingMemoryBound(to: Status.self).pointee {
    case .active: return 0
    case .inactive: return 1
    case .suspended: return 2
    }
}

private func statusProjectActiveBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func statusProjectActiveInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func statusDropActiveProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func statusConstructActive(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: Status.self).initialize(to: .active)
    return true
}

private func statusProjectInactiveBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func statusProjectInactiveInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func statusDropInactiveProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func statusConstructInactive(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: Status.self).initialize(to: .inactive)
    return true
}

private func statusProjectSuspendedBorrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {
    nil
}

private func statusProjectSuspendedInto(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    outLen == 0
}

private func statusDropSuspendedProjected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {}

private func statusConstructSuspended(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {
    guard payloadLen == 0 else { return false }
    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: Status.self).initialize(to: .suspended)
    return true
}

private func descriptorForUInt32(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    arena.plain(typeID: binette_primitive_u32_type_id(), UInt32.self)
}

private func descriptorForTag(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0x0EEFCCA6337B755D,
        layout: binetteLayout(of: Tag.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("label"),
                offset: MemoryLayout<Tag>.offset(of: \Tag.label)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("priority"),
                offset: MemoryLayout<Tag>.offset(of: \Tag.priority)!,
                descriptor: descriptorForUInt32(in: arena)
            ),
        ]
    )
}

private func descriptorForMeasurement(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0x4F3C1DD93CA2D25F,
        layout: binetteLayout(of: Measurement.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("unit"),
                offset: MemoryLayout<Measurement>.offset(of: \Measurement.unit)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("value"),
                offset: MemoryLayout<Measurement>.offset(of: \Measurement.value)!,
                descriptor: descriptorForString(in: arena)
            ),
        ]
    )
}

private func descriptorForConfig(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.structure(
        typeID: 0x4D9687F8912787EE,
        layout: binetteLayout(of: Config.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("key"),
                offset: MemoryLayout<Config>.offset(of: \Config.key)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("value"),
                offset: MemoryLayout<Config>.offset(of: \Config.value)!,
                descriptor: descriptorForString(in: arena)
            ),
            BinetteLocalFieldAbi(
                name: binetteLocalStr("owner"),
                offset: MemoryLayout<Config>.offset(of: \Config.owner)!,
                descriptor: descriptorForString(in: arena)
            ),
        ]
    )
}

private func descriptorForTestbedEchoProfileArgs(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.tuple(
        typeID: 0x1C872ABDDEEBEB04,
        layout: binetteLayout(of: TestbedEchoProfileArgs.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("0"),
                offset: MemoryLayout<TestbedEchoProfileArgs>.offset(of: \TestbedEchoProfileArgs.profile)!,
                descriptor: descriptorForProfile(in: arena)
            ),
        ]
    )
}

private func descriptorForTestbedEchoRecordArgs(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.tuple(
        typeID: 0xB117EE08DA4B8F1A,
        layout: binetteLayout(of: TestbedEchoRecordArgs.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("0"),
                offset: MemoryLayout<TestbedEchoRecordArgs>.offset(of: \TestbedEchoRecordArgs.record)!,
                descriptor: descriptorForRecord(in: arena)
            ),
        ]
    )
}

private func descriptorForTestbedEchoStatusArgs(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.tuple(
        typeID: 0xC86970D3FFC36703,
        layout: binetteLayout(of: TestbedEchoStatusArgs.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("0"),
                offset: MemoryLayout<TestbedEchoStatusArgs>.offset(of: \TestbedEchoStatusArgs.status)!,
                descriptor: descriptorForStatus(in: arena)
            ),
        ]
    )
}

private func descriptorForTestbedEchoTagArgs(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.tuple(
        typeID: 0x8ACD53149D73CE97,
        layout: binetteLayout(of: TestbedEchoTagArgs.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("0"),
                offset: MemoryLayout<TestbedEchoTagArgs>.offset(of: \TestbedEchoTagArgs.tag)!,
                descriptor: descriptorForTag(in: arena)
            ),
        ]
    )
}

private func descriptorForTestbedEchoMeasurementArgs(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.tuple(
        typeID: 0x9A21C2B015FA1A3F,
        layout: binetteLayout(of: TestbedEchoMeasurementArgs.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("0"),
                offset: MemoryLayout<TestbedEchoMeasurementArgs>.offset(of: \TestbedEchoMeasurementArgs.m)!,
                descriptor: descriptorForMeasurement(in: arena)
            ),
        ]
    )
}

private func descriptorForTestbedEchoConfigArgs(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {
    return arena.tuple(
        typeID: 0x4026A77FB964CE28,
        layout: binetteLayout(of: TestbedEchoConfigArgs.self),
        fields: [
            BinetteLocalFieldAbi(
                name: binetteLocalStr("0"),
                offset: MemoryLayout<TestbedEchoConfigArgs>.offset(of: \TestbedEchoConfigArgs.c)!,
                descriptor: descriptorForConfig(in: arena)
            ),
        ]
    )
}

// Method codecs
public final class TestbedMethodCodecs {
    private let arena = BinetteCAbiDescriptorArena()

    public init() {}

    public func echoProfile() throws -> VoxSwiftMethodCodec {
        try VoxSwiftMethodCodec(
            methodId: 0xBD9BCABDDEEBEB04,
            argsDescriptor: descriptorForTestbedEchoProfileArgs(in: arena),
            responseDescriptor: descriptorForProfile(in: arena)
        )
    }

    public func echoRecord() throws -> VoxSwiftMethodCodec {
        try VoxSwiftMethodCodec(
            methodId: 0x100B0E08DA4B8F1A,
            argsDescriptor: descriptorForTestbedEchoRecordArgs(in: arena),
            responseDescriptor: descriptorForRecord(in: arena)
        )
    }

    public func echoStatus() throws -> VoxSwiftMethodCodec {
        try VoxSwiftMethodCodec(
            methodId: 0x697590D3FFC36703,
            argsDescriptor: descriptorForTestbedEchoStatusArgs(in: arena),
            responseDescriptor: descriptorForStatus(in: arena)
        )
    }

    public func echoTag() throws -> VoxSwiftMethodCodec {
        try VoxSwiftMethodCodec(
            methodId: 0x2BD1B3149D73CE97,
            argsDescriptor: descriptorForTestbedEchoTagArgs(in: arena),
            responseDescriptor: descriptorForTag(in: arena)
        )
    }

    public func echoMeasurement() throws -> VoxSwiftMethodCodec {
        try VoxSwiftMethodCodec(
            methodId: 0x3B3D22B015FA1A3F,
            argsDescriptor: descriptorForTestbedEchoMeasurementArgs(in: arena),
            responseDescriptor: descriptorForMeasurement(in: arena)
        )
    }

    public func echoConfig() throws -> VoxSwiftMethodCodec {
        try VoxSwiftMethodCodec(
            methodId: 0xE13A477FB964CE28,
            argsDescriptor: descriptorForTestbedEchoConfigArgs(in: arena),
            responseDescriptor: descriptorForConfig(in: arena)
        )
    }

}
