//! Swift code generation for binette local-access descriptors.
//!
//! This target emits Swift that describes local Swift values through the
//! binette C ABI descriptor surface. It does not emit a separate Swift codec.

use std::collections::BTreeSet;

use facet_core::{ScalarType, Shape};
use heck::{ToLowerCamelCase, ToUpperCamelCase};
use vox_types::{
    EnumInfo, SchemaHash, ServiceDescriptor, ShapeKind, StructInfo, TypeRef, VariantKind,
    classify_shape, classify_variant, extract_schemas, is_bytes,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SwiftCodegenError {
    Schema(String),
    UnsupportedShape { shape: String, reason: String },
}

impl std::fmt::Display for SwiftCodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Schema(message) => write!(f, "swift codegen schema extraction failed: {message}"),
            Self::UnsupportedShape { shape, reason } => {
                write!(f, "swift codegen does not support {shape}: {reason}")
            }
        }
    }
}

impl std::error::Error for SwiftCodegenError {}

#[derive(Clone)]
struct NamedShape {
    name: String,
    shape: &'static Shape,
}

struct SwiftGenerator<'a> {
    service: &'a ServiceDescriptor,
    named: Vec<NamedShape>,
    generated_descriptors: BTreeSet<String>,
    output: String,
}

pub fn generate_service(service: &ServiceDescriptor) -> Result<String, SwiftCodegenError> {
    SwiftGenerator {
        service,
        named: collect_named_shapes(service),
        generated_descriptors: BTreeSet::new(),
        output: String::new(),
    }
    .generate()
}

impl<'a> SwiftGenerator<'a> {
    fn generate(mut self) -> Result<String, SwiftCodegenError> {
        self.line("// @generated by vox-codegen");
        self.line("// DO NOT EDIT - regenerate with `cargo xtask codegen --swift`");
        self.line("");
        self.line("import BinetteSwiftProbes");
        self.line("import CBinette");
        self.line("import VoxSwift");
        self.line("");

        self.emit_named_types()?;
        self.emit_variant_payload_types()?;
        self.emit_method_arg_types()?;
        self.emit_descriptor_helpers()?;
        self.emit_method_codecs()?;

        Ok(self.output)
    }

    fn emit_named_types(&mut self) -> Result<(), SwiftCodegenError> {
        if self.named.is_empty() {
            return Ok(());
        }
        self.line("// Named value types");
        let named = self.named.clone();
        for item in &named {
            match classify_shape(item.shape) {
                ShapeKind::Struct(StructInfo { fields, .. }) => {
                    self.line(&format!("public struct {} {{", item.name));
                    for field in fields {
                        self.line(&format!(
                            "    public var {}: {}",
                            swift_ident(field.name),
                            swift_type(field.shape())?
                        ));
                    }
                    self.emit_public_init(
                        "    ",
                        fields
                            .iter()
                            .map(|field| FieldLike {
                                name: field.name.to_owned(),
                                swift_field: swift_ident(field.name),
                                shape: field.shape(),
                            })
                            .collect::<Vec<_>>()
                            .as_slice(),
                    )?;
                    self.line("}");
                    self.line("");
                }
                ShapeKind::Enum(EnumInfo { variants, .. }) => {
                    self.line(&format!("public enum {} {{", item.name));
                    for variant in variants {
                        match classify_variant(variant) {
                            VariantKind::Unit => {
                                self.line(&format!("    case {}", swift_ident(variant.name)));
                            }
                            VariantKind::Newtype { inner } => {
                                self.line(&format!(
                                    "    case {}({})",
                                    swift_ident(variant.name),
                                    swift_type(inner)?
                                ));
                            }
                            VariantKind::Tuple { fields } => {
                                let fields = fields
                                    .iter()
                                    .map(|field| swift_type(field.shape()))
                                    .collect::<Result<Vec<_>, _>>()?
                                    .join(", ");
                                self.line(&format!(
                                    "    case {}({fields})",
                                    swift_ident(variant.name)
                                ));
                            }
                            VariantKind::Struct { fields } => {
                                let fields = fields
                                    .iter()
                                    .map(|field| {
                                        Ok(format!(
                                            "{}: {}",
                                            swift_ident(field.name),
                                            swift_type(field.shape())?
                                        ))
                                    })
                                    .collect::<Result<Vec<_>, SwiftCodegenError>>()?
                                    .join(", ");
                                self.line(&format!(
                                    "    case {}({fields})",
                                    swift_ident(variant.name)
                                ));
                            }
                        }
                    }
                    self.line("}");
                    self.line("");
                }
                _ => {}
            }
        }
        Ok(())
    }

    fn emit_variant_payload_types(&mut self) -> Result<(), SwiftCodegenError> {
        let named = self.named.clone();
        let mut emitted_header = false;
        for item in &named {
            let ShapeKind::Enum(EnumInfo { variants, .. }) = classify_shape(item.shape) else {
                continue;
            };
            for variant in variants {
                match classify_variant(variant) {
                    VariantKind::Tuple { fields } | VariantKind::Struct { fields } => {
                        if !emitted_header {
                            self.line("// Enum payload carriers");
                            emitted_header = true;
                        }
                        self.emit_variant_payload_type(&item.name, variant, fields)?;
                    }
                    VariantKind::Unit | VariantKind::Newtype { .. } => {}
                }
            }
        }
        if emitted_header {
            self.line("");
        }
        Ok(())
    }

    fn emit_variant_payload_type(
        &mut self,
        enum_type_name: &str,
        variant: &facet_core::Variant,
        fields: &[facet_core::Field],
    ) -> Result<(), SwiftCodegenError> {
        let payload_type = variant_payload_type_name(enum_type_name, variant.name);
        self.line(&format!("private struct {payload_type} {{"));
        for field in variant_payload_fields(variant, fields)? {
            self.line(&format!(
                "    var {}: {}",
                field.swift_field,
                swift_type(field.shape)?
            ));
        }
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_method_arg_types(&mut self) -> Result<(), SwiftCodegenError> {
        self.line("// Method argument tuple carriers");
        for method in self.service.methods {
            let args_type = method_args_type(self.service, method.method_name);
            self.line(&format!("public struct {args_type} {{"));
            for arg in method.args {
                self.line(&format!(
                    "    public var {}: {}",
                    swift_ident(arg.name),
                    swift_type(arg.shape)?
                ));
            }
            self.emit_public_init(
                "    ",
                method
                    .args
                    .iter()
                    .map(|arg| FieldLike {
                        name: arg.name.to_owned(),
                        swift_field: swift_ident(arg.name),
                        shape: arg.shape,
                    })
                    .collect::<Vec<_>>()
                    .as_slice(),
            )?;
            self.line("}");
            self.line("");
        }
        Ok(())
    }

    fn emit_descriptor_helpers(&mut self) -> Result<(), SwiftCodegenError> {
        self.line("// Local binette descriptors");
        let named = self.named.clone();
        for item in &named {
            self.emit_shape_descriptor(item.shape)?;
        }
        for method in self.service.methods {
            self.emit_method_args_descriptor(method)?;
            self.emit_shape_descriptor(method.return_shape)?;
        }
        Ok(())
    }

    fn emit_method_codecs(&mut self) -> Result<(), SwiftCodegenError> {
        self.line("// Method codecs");
        self.line(&format!(
            "public final class {}MethodCodecs {{",
            self.service.service_name.to_upper_camel_case()
        ));
        self.line("    private let arena = BinetteCAbiDescriptorArena()");
        self.line("");
        self.line("    public init() {}");
        self.line("");
        for method in self.service.methods {
            let method_name = swift_ident(&method.method_name.to_lower_camel_case());
            let args_descriptor = method_args_descriptor_name(self.service, method.method_name);
            let response_descriptor = descriptor_fn_name(method.return_shape)?;
            self.line(&format!(
                "    public func {method_name}() throws -> VoxSwiftMethodCodec {{"
            ));
            self.line("        try VoxSwiftMethodCodec(");
            self.line(&format!(
                "            argsDescriptor: {args_descriptor}(in: arena),"
            ));
            self.line(&format!(
                "            responseDescriptor: {response_descriptor}(in: arena)"
            ));
            self.line("        )");
            self.line("    }");
            self.line("");
        }
        self.line("}");
        Ok(())
    }

    fn emit_method_args_descriptor(
        &mut self,
        method: &vox_types::MethodDescriptor,
    ) -> Result<(), SwiftCodegenError> {
        let fn_name = method_args_descriptor_name(self.service, method.method_name);
        if !self.generated_descriptors.insert(fn_name.clone()) {
            return Ok(());
        }
        for arg in method.args {
            self.emit_shape_descriptor(arg.shape)?;
        }

        let args_type = method_args_type(self.service, method.method_name);
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.line("    return arena.tuple(");
        self.line(&format!(
            "        typeID: {},",
            hex_u64(method.id.0 ^ 0xA11C_E000_0000_0000)
        ));
        self.line(&format!(
            "        layout: binetteLayout(of: {args_type}.self),"
        ));
        self.line("        fields: [");
        for (index, arg) in method.args.iter().enumerate() {
            self.line("            BinetteLocalFieldAbi(");
            self.line(&format!(
                "                name: binetteLocalStr(\"{index}\"),"
            ));
            self.line(&format!(
                "                offset: MemoryLayout<{args_type}>.offset(of: \\{}.{})!,",
                args_type,
                swift_ident(arg.name)
            ));
            self.line(&format!(
                "                descriptor: {}(in: arena)",
                descriptor_fn_name(arg.shape)?
            ));
            self.line("            ),");
        }
        self.line("        ]");
        self.line("    )");
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_shape_descriptor(&mut self, shape: &'static Shape) -> Result<(), SwiftCodegenError> {
        let fn_name = descriptor_fn_name(shape)?;
        if !self.generated_descriptors.insert(fn_name.clone()) {
            return Ok(());
        }

        match classify_shape(shape) {
            ShapeKind::Scalar(scalar) => self.emit_scalar_descriptor(&fn_name, scalar),
            ShapeKind::List { .. } | ShapeKind::Slice { .. } if is_bytes(shape) => {
                self.emit_bytes_descriptor(&fn_name)
            }
            ShapeKind::Option { inner } => self.emit_option_descriptor(&fn_name, shape, inner),
            ShapeKind::Tx { inner } | ShapeKind::Rx { inner } => {
                self.emit_channel_descriptor(&fn_name, shape, inner)
            }
            ShapeKind::Struct(StructInfo { fields, .. }) => {
                for field in fields {
                    self.emit_shape_descriptor(field.shape())?;
                }
                self.emit_struct_descriptor(&fn_name, shape, fields)
            }
            ShapeKind::Enum(EnumInfo { variants, .. }) => {
                for variant in variants {
                    match classify_variant(variant) {
                        VariantKind::Newtype { inner } => self.emit_shape_descriptor(inner)?,
                        VariantKind::Tuple { fields } | VariantKind::Struct { fields } => {
                            for field in fields {
                                self.emit_shape_descriptor(field.shape())?;
                            }
                        }
                        VariantKind::Unit => {}
                    }
                }
                self.emit_enum_descriptor(&fn_name, shape, variants)
            }
            ShapeKind::Tuple { elements } => {
                for element in elements {
                    self.emit_shape_descriptor(element.shape)?;
                }
                self.emit_tuple_descriptor(
                    &fn_name,
                    shape,
                    &elements
                        .iter()
                        .enumerate()
                        .map(|(index, element)| FieldLike {
                            name: index.to_string(),
                            swift_field: index.to_string(),
                            shape: element.shape,
                        })
                        .collect::<Vec<_>>(),
                )
            }
            _ => Err(unsupported(
                shape,
                "no Swift C ABI descriptor emitter for this shape yet",
            )),
        }
    }

    fn emit_scalar_descriptor(
        &mut self,
        fn_name: &str,
        scalar: ScalarType,
    ) -> Result<(), SwiftCodegenError> {
        let (type_id, swift_type) = match scalar {
            ScalarType::Bool => ("binette_primitive_bool_type_id()", "Bool"),
            ScalarType::U8 => ("binette_primitive_u8_type_id()", "UInt8"),
            ScalarType::U16 => ("binette_primitive_u16_type_id()", "UInt16"),
            ScalarType::U32 => ("binette_primitive_u32_type_id()", "UInt32"),
            ScalarType::U64 => ("binette_primitive_u64_type_id()", "UInt64"),
            ScalarType::I32 => ("binette_primitive_i32_type_id()", "Int32"),
            ScalarType::I64 => ("binette_primitive_i64_type_id()", "Int64"),
            ScalarType::F64 => ("binette_primitive_f64_type_id()", "Double"),
            ScalarType::Str | ScalarType::String | ScalarType::CowStr => {
                self.line(&format!(
                    "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
                ));
                self.line("    arena.string()");
                self.line("}");
                self.line("");
                return Ok(());
            }
            _ => {
                return Err(SwiftCodegenError::UnsupportedShape {
                    shape: format!("{scalar:?}"),
                    reason: "primitive is not exported by the current binette Swift C ABI"
                        .to_owned(),
                });
            }
        };
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.line(&format!(
            "    arena.plain(typeID: {type_id}, {swift_type}.self)"
        ));
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_bytes_descriptor(&mut self, fn_name: &str) -> Result<(), SwiftCodegenError> {
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.line("    arena.bytes()");
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_option_descriptor(
        &mut self,
        fn_name: &str,
        shape: &'static Shape,
        inner: &'static Shape,
    ) -> Result<(), SwiftCodegenError> {
        self.emit_shape_descriptor(inner)?;
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.line(&format!(
            "    let some = {}(in: arena)",
            descriptor_fn_name(inner)?
        ));
        let (swift_type, representation) = match classify_shape(inner) {
            ShapeKind::Scalar(ScalarType::U16) => {
                ("UInt16", "binetteDirectOptionalU16Representation()")
            }
            ShapeKind::Scalar(ScalarType::Str | ScalarType::String | ScalarType::CowStr) => {
                ("String", "binetteThunkOptionalStringRepresentation()")
            }
            _ => {
                return Err(unsupported(
                    shape,
                    "no Swift C ABI optional representation helper for this payload yet",
                ));
            }
        };
        self.line("    return arena.option(");
        self.line(&format!(
            "        typeID: {},",
            synthetic_type_id(shape, 0x0F10_0000_0000_0000)?
        ));
        self.line(&format!(
            "        layout: binetteLayout(of: {swift_type}?.self),"
        ));
        self.line("        some: some,");
        self.line(&format!("        representation: {representation}"));
        self.line("    )");
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_channel_descriptor(
        &mut self,
        fn_name: &str,
        shape: &'static Shape,
        inner: &'static Shape,
    ) -> Result<(), SwiftCodegenError> {
        self.emit_shape_descriptor(inner)?;
        let direction = match classify_shape(shape) {
            ShapeKind::Tx { .. } => "tx",
            ShapeKind::Rx { .. } => "rx",
            _ => unreachable!(),
        };
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.line("    return arena.externalAttachment(");
        self.line(&format!(
            "        typeID: {},",
            synthetic_type_id(shape, 0x0E71_0000_0000_0000)?
        ));
        self.line("        kind: \"vox.channel\",");
        self.line("        layout: binetteLayout(of: VoxSwiftChannel.self),");
        self.line("        metadataFields: [");
        self.line("            arena.externalMetadataField(");
        self.line("                \"direction\",");
        self.line(&format!(
            "                arena.externalMetadataString(\"{direction}\")"
        ));
        self.line("            ),");
        self.line("            arena.externalMetadataField(");
        self.line("                \"element\",");
        self.line(&format!(
            "                arena.externalMetadataTypeRef({}(in: arena))",
            descriptor_fn_name(inner)?
        ));
        self.line("            ),");
        self.line("        ]");
        self.line("    )");
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_struct_descriptor(
        &mut self,
        fn_name: &str,
        shape: &'static Shape,
        fields: &[facet_core::Field],
    ) -> Result<(), SwiftCodegenError> {
        let type_name = swift_shape_type(shape)?;
        let fields = fields
            .iter()
            .map(|field| FieldLike {
                name: field.name.to_owned(),
                swift_field: swift_ident(field.name),
                shape: field.shape(),
            })
            .collect::<Vec<_>>();
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.emit_aggregate_body("structure", shape, &type_name, &fields)
    }

    fn emit_tuple_descriptor(
        &mut self,
        fn_name: &str,
        shape: &'static Shape,
        fields: &[FieldLike],
    ) -> Result<(), SwiftCodegenError> {
        let type_name = swift_shape_type(shape)?;
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.emit_aggregate_body("tuple", shape, &type_name, fields)
    }

    fn emit_aggregate_body(
        &mut self,
        kind: &str,
        shape: &'static Shape,
        type_name: &str,
        fields: &[FieldLike],
    ) -> Result<(), SwiftCodegenError> {
        let type_id = concrete_or_synthetic_type_id(shape)?;
        self.emit_aggregate_body_with_type_id(kind, &type_id, type_name, fields)
    }

    fn emit_aggregate_body_with_type_id(
        &mut self,
        kind: &str,
        type_id: &str,
        type_name: &str,
        fields: &[FieldLike],
    ) -> Result<(), SwiftCodegenError> {
        self.line(&format!("    return arena.{kind}("));
        self.line(&format!("        typeID: {type_id},"));
        self.line(&format!(
            "        layout: binetteLayout(of: {type_name}.self),"
        ));
        self.line("        fields: [");
        for field in fields {
            self.line("            BinetteLocalFieldAbi(");
            self.line(&format!(
                "                name: binetteLocalStr(\"{}\"),",
                field.name
            ));
            self.line(&format!(
                "                offset: MemoryLayout<{type_name}>.offset(of: \\{}.{})!,",
                type_name, field.swift_field
            ));
            self.line(&format!(
                "                descriptor: {}(in: arena)",
                descriptor_fn_name(field.shape)?
            ));
            self.line("            ),");
        }
        self.line("        ]");
        self.line("    )");
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_enum_descriptor(
        &mut self,
        fn_name: &str,
        shape: &'static Shape,
        variants: &[facet_core::Variant],
    ) -> Result<(), SwiftCodegenError> {
        let type_name = swift_shape_type(shape)?;
        for (index, variant) in variants.iter().enumerate() {
            match classify_variant(variant) {
                VariantKind::Tuple { fields } | VariantKind::Struct { fields } => {
                    self.emit_variant_payload_descriptor(
                        shape, &type_name, variant, index, fields,
                    )?;
                }
                VariantKind::Unit | VariantKind::Newtype { .. } => {}
            }
        }
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.line("    return arena.enumeration(");
        self.line(&format!(
            "        typeID: {},",
            concrete_or_synthetic_type_id(shape)?
        ));
        self.line(&format!(
            "        layout: binetteLayout(of: {type_name}.self),"
        ));
        self.line("        tag: BinetteLocalEnumTagAccessAbi(");
        self.line("            tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),");
        self.line("            direct_offset: 0,");
        self.line(&format!(
            "            thunk: BinetteLocalEnumTagThunkAbi(call: {}Tag, context: nil)",
            type_name.to_lower_camel_case()
        ));
        self.line("        ),");
        self.line("        variants: [");
        for (index, variant) in variants.iter().enumerate() {
            self.emit_variant_descriptor(&type_name, variant, index)?;
        }
        self.line("        ]");
        self.line("    )");
        self.line("}");
        self.line("");
        self.emit_enum_thunks(&type_name, variants)?;
        Ok(())
    }

    fn emit_variant_descriptor(
        &mut self,
        type_name: &str,
        variant: &facet_core::Variant,
        index: usize,
    ) -> Result<(), SwiftCodegenError> {
        self.line("            BinetteLocalVariantAbi(");
        self.line(&format!(
            "                name: binetteLocalStr(\"{}\"),",
            variant.name
        ));
        self.line(&format!("                index: {index},"));
        self.line("                project: BinetteLocalVariantProjectAccessAbi(");
        self.line("                    tag: UInt32(BINETTE_LOCAL_ACCESS_THUNK),");
        self.line("                    direct_offset: 0,");
        self.line(&format!(
            "                    thunk: BinetteLocalVariantProjectThunkAbi(call: {}Project{}Borrowed, context: nil)",
            type_name.to_lower_camel_case(),
            variant.name.to_upper_camel_case()
        ));
        self.line("                ),");
        self.line("                project_into: BinetteLocalVariantProjectIntoAbi(");
        self.line(&format!(
            "                    call: {}Project{}Into,",
            type_name.to_lower_camel_case(),
            variant.name.to_upper_camel_case()
        ));
        self.line("                    context: nil");
        self.line("                ),");
        self.line("                drop_projected: BinetteLocalVariantDropAbi(");
        self.line(&format!(
            "                    call: {}Drop{}Projected,",
            type_name.to_lower_camel_case(),
            variant.name.to_upper_camel_case()
        ));
        self.line("                    context: nil");
        self.line("                ),");
        self.line("                construct: BinetteLocalVariantConstructAbi(");
        self.line(&format!(
            "                    call: {}Construct{},",
            type_name.to_lower_camel_case(),
            variant.name.to_upper_camel_case()
        ));
        self.line("                    context: nil");
        self.line("                ),");
        let payload = match classify_variant(variant) {
            VariantKind::Unit => "nil".to_owned(),
            VariantKind::Newtype { inner } => format!("{}(in: arena)", descriptor_fn_name(inner)?),
            VariantKind::Tuple { .. } | VariantKind::Struct { .. } => {
                format!(
                    "{}(in: arena)",
                    variant_payload_descriptor_name(type_name, variant.name)
                )
            }
        };
        self.line(&format!("                payload: {payload}"));
        self.line("            ),");
        Ok(())
    }

    fn emit_variant_payload_descriptor(
        &mut self,
        owner_shape: &'static Shape,
        enum_type_name: &str,
        variant: &facet_core::Variant,
        index: usize,
        fields: &[facet_core::Field],
    ) -> Result<(), SwiftCodegenError> {
        let fn_name = variant_payload_descriptor_name(enum_type_name, variant.name);
        if !self.generated_descriptors.insert(fn_name.clone()) {
            return Ok(());
        }
        let payload_type = variant_payload_type_name(enum_type_name, variant.name);
        let fields = variant_payload_fields(variant, fields)?;
        let type_id = synthetic_type_id(owner_shape, 0x9A7E_0000_0000_0000 ^ index as u64)?;
        let kind = match classify_variant(variant) {
            VariantKind::Tuple { .. } => "tuple",
            VariantKind::Struct { .. } => "structure",
            VariantKind::Unit | VariantKind::Newtype { .. } => unreachable!(),
        };
        self.line(&format!(
            "private func {fn_name}(in arena: BinetteCAbiDescriptorArena) -> UnsafePointer<BinetteLocalDescriptorAbi> {{"
        ));
        self.emit_aggregate_body_with_type_id(kind, &type_id, &payload_type, &fields)
    }

    fn emit_enum_thunks(
        &mut self,
        type_name: &str,
        variants: &[facet_core::Variant],
    ) -> Result<(), SwiftCodegenError> {
        let prefix = type_name.to_lower_camel_case();
        self.line(&format!(
            "private func {prefix}Tag(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UInt32 {{"
        ));
        self.line(&format!(
            "    switch UnsafeRawPointer(value!).assumingMemoryBound(to: {type_name}.self).pointee {{"
        ));
        for (index, variant) in variants.iter().enumerate() {
            let pattern = match classify_variant(variant) {
                VariantKind::Unit => format!(".{}", swift_ident(variant.name)),
                VariantKind::Newtype { .. } => format!(".{}(_)", swift_ident(variant.name)),
                VariantKind::Tuple { fields } | VariantKind::Struct { fields } => {
                    format!(
                        ".{}({})",
                        swift_ident(variant.name),
                        (0..fields.len())
                            .map(|_| "_")
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                }
            };
            self.line(&format!("    case {pattern}: return {index}",));
        }
        self.line("    }");
        self.line("}");
        self.line("");

        for variant in variants {
            let variant_camel = variant.name.to_upper_camel_case();
            self.line(&format!(
                "private func {prefix}Project{variant_camel}Borrowed(_ value: UnsafePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) -> UnsafePointer<UInt8>? {{"
            ));
            self.line("    nil");
            self.line("}");
            self.line("");

            match classify_variant(variant) {
                VariantKind::Unit => {
                    self.emit_unit_variant_thunks(type_name, variant)?;
                }
                VariantKind::Newtype { inner } => {
                    self.emit_newtype_variant_thunks(type_name, variant, inner)?;
                }
                VariantKind::Tuple { fields } | VariantKind::Struct { fields } => {
                    self.emit_aggregate_variant_thunks(type_name, variant, fields)?;
                }
            }
        }
        Ok(())
    }

    fn emit_unit_variant_thunks(
        &mut self,
        type_name: &str,
        variant: &facet_core::Variant,
    ) -> Result<(), SwiftCodegenError> {
        let prefix = type_name.to_lower_camel_case();
        let variant_camel = variant.name.to_upper_camel_case();
        self.line(&format!(
            "private func {prefix}Project{variant_camel}Into(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {{"
        ));
        self.line("    outLen == 0");
        self.line("}");
        self.line("");
        self.line(&format!(
            "private func {prefix}Drop{variant_camel}Projected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {{}}"
        ));
        self.line("");
        self.line(&format!(
            "private func {prefix}Construct{variant_camel}(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {{"
        ));
        self.line("    guard payloadLen == 0 else { return false }");
        self.line(&format!(
            "    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: {type_name}.self).initialize(to: .{})",
            swift_ident(variant.name)
        ));
        self.line("    return true");
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_aggregate_variant_thunks(
        &mut self,
        type_name: &str,
        variant: &facet_core::Variant,
        fields: &[facet_core::Field],
    ) -> Result<(), SwiftCodegenError> {
        let prefix = type_name.to_lower_camel_case();
        let variant_camel = variant.name.to_upper_camel_case();
        let variant_ident = swift_ident(variant.name);
        let payload_type = variant_payload_type_name(type_name, variant.name);
        let is_tuple = matches!(classify_variant(variant), VariantKind::Tuple { .. });
        let fields = variant_payload_fields(variant, fields)?;
        let binding_names = fields
            .iter()
            .map(|field| field.swift_field.clone())
            .collect::<Vec<_>>();
        let pattern = binding_names.join(", ");
        let init_args = fields
            .iter()
            .map(|field| format!("{}: {}", field.swift_field, field.swift_field))
            .collect::<Vec<_>>()
            .join(", ");
        let construct_args = fields
            .iter()
            .map(|field| {
                if is_tuple {
                    format!("payloadValue.{}", field.swift_field)
                } else {
                    format!("{}: payloadValue.{}", field.swift_field, field.swift_field)
                }
            })
            .collect::<Vec<_>>()
            .join(", ");

        self.line(&format!(
            "private func {prefix}Project{variant_camel}Into(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {{"
        ));
        self.line(&format!(
            "    guard outLen == MemoryLayout<{payload_type}>.size else {{ return false }}"
        ));
        self.line(&format!(
            "    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: {type_name}.self).pointee"
        ));
        self.line(&format!(
            "    guard case let .{variant_ident}({pattern}) = value else {{ return false }}"
        ));
        self.line(&format!(
            "    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: {payload_type}.self).initialize(to: {payload_type}({init_args}))"
        ));
        self.line("    return true");
        self.line("}");
        self.line("");

        self.line(&format!(
            "private func {prefix}Drop{variant_camel}Projected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {{"
        ));
        self.line(&format!(
            "    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: {payload_type}.self).deinitialize(count: 1)"
        ));
        self.line("}");
        self.line("");

        self.line(&format!(
            "private func {prefix}Construct{variant_camel}(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {{"
        ));
        self.line(&format!(
            "    guard payloadLen == MemoryLayout<{payload_type}>.size else {{ return false }}"
        ));
        self.line(&format!(
            "    let payloadValue = UnsafeRawPointer(payloadBytes!).assumingMemoryBound(to: {payload_type}.self).pointee"
        ));
        self.line(&format!(
            "    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: {type_name}.self).initialize(to: .{variant_ident}({construct_args}))"
        ));
        self.line("    return true");
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_newtype_variant_thunks(
        &mut self,
        type_name: &str,
        variant: &facet_core::Variant,
        inner: &'static Shape,
    ) -> Result<(), SwiftCodegenError> {
        let prefix = type_name.to_lower_camel_case();
        let variant_camel = variant.name.to_upper_camel_case();
        let inner_type = swift_type(inner)?;
        let variant_ident = swift_ident(variant.name);
        self.line(&format!(
            "private func {prefix}Project{variant_camel}Into(_ value: UnsafePointer<UInt8>?, _ out: UnsafeMutablePointer<UInt8>?, _ outLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {{"
        ));
        self.line(&format!(
            "    guard outLen == MemoryLayout<{inner_type}>.size else {{ return false }}"
        ));
        self.line(&format!(
            "    let value = UnsafeRawPointer(value!).assumingMemoryBound(to: {type_name}.self).pointee"
        ));
        self.line(&format!(
            "    guard case let .{variant_ident}(payload) = value else {{ return false }}"
        ));
        self.line(&format!(
            "    UnsafeMutableRawPointer(out!).assumingMemoryBound(to: {inner_type}.self).initialize(to: payload)"
        ));
        self.line("    return true");
        self.line("}");
        self.line("");

        self.line(&format!(
            "private func {prefix}Drop{variant_camel}Projected(_ value: UnsafeMutablePointer<UInt8>?, _ context: UnsafeMutableRawPointer?) {{"
        ));
        self.line(&format!(
            "    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: {inner_type}.self).deinitialize(count: 1)"
        ));
        self.line("}");
        self.line("");

        self.line(&format!(
            "private func {prefix}Construct{variant_camel}(_ value: UnsafeMutablePointer<UInt8>?, _ payloadBytes: UnsafePointer<UInt8>?, _ payloadLen: Int, _ context: UnsafeMutableRawPointer?) -> Bool {{"
        ));
        match classify_shape(inner) {
            ShapeKind::Scalar(ScalarType::Str | ScalarType::String | ScalarType::CowStr) => {
                self.line(
                    "    let bytes = UnsafeBufferPointer(start: payloadBytes, count: payloadLen)",
                );
                self.line("    guard let payloadValue = String(bytes: bytes, encoding: .utf8) else { return false }");
            }
            ShapeKind::Scalar(ScalarType::U32) => {
                self.line(
                    "    guard payloadLen == MemoryLayout<UInt32>.size else { return false }",
                );
                self.line("    var payloadValue: UInt32 = 0");
                self.line("    withUnsafeMutableBytes(of: &payloadValue) { out in");
                self.line("        out.copyMemory(from: UnsafeRawBufferPointer(start: payloadBytes, count: payloadLen))");
                self.line("    }");
            }
            _ => {
                return Err(unsupported(
                    inner,
                    "enum newtype construction currently supports String and UInt32 payload bytes",
                ));
            }
        }
        self.line(&format!(
            "    UnsafeMutableRawPointer(value!).assumingMemoryBound(to: {type_name}.self).initialize(to: .{variant_ident}(payloadValue))"
        ));
        self.line("    return true");
        self.line("}");
        self.line("");
        Ok(())
    }

    fn emit_public_init(
        &mut self,
        indent: &str,
        fields: &[FieldLike],
    ) -> Result<(), SwiftCodegenError> {
        if fields.is_empty() {
            self.line(&format!("{indent}public init() {{}}"));
            return Ok(());
        }

        let args = fields
            .iter()
            .map(|field| {
                Ok(format!(
                    "{}: {}",
                    field.swift_field,
                    swift_type(field.shape)?
                ))
            })
            .collect::<Result<Vec<_>, SwiftCodegenError>>()?
            .join(", ");
        self.line(&format!("{indent}public init({args}) {{"));
        for field in fields {
            self.line(&format!(
                "{indent}    self.{} = {}",
                field.swift_field, field.swift_field
            ));
        }
        self.line(&format!("{indent}}}"));
        Ok(())
    }

    fn line(&mut self, line: &str) {
        self.output.push_str(line);
        self.output.push('\n');
    }
}

#[derive(Clone)]
struct FieldLike {
    name: String,
    swift_field: String,
    shape: &'static Shape,
}

fn variant_payload_type_name(enum_type_name: &str, variant_name: &str) -> String {
    format!(
        "{}{}Payload",
        enum_type_name,
        variant_name.to_upper_camel_case()
    )
}

fn variant_payload_descriptor_name(enum_type_name: &str, variant_name: &str) -> String {
    format!(
        "descriptorFor{}{}Payload",
        enum_type_name,
        variant_name.to_upper_camel_case()
    )
}

fn variant_payload_fields(
    variant: &facet_core::Variant,
    fields: &[facet_core::Field],
) -> Result<Vec<FieldLike>, SwiftCodegenError> {
    match classify_variant(variant) {
        VariantKind::Tuple { .. } => Ok(fields
            .iter()
            .enumerate()
            .map(|(index, field)| FieldLike {
                name: index.to_string(),
                swift_field: format!("field{index}"),
                shape: field.shape(),
            })
            .collect()),
        VariantKind::Struct { .. } => Ok(fields
            .iter()
            .map(|field| FieldLike {
                name: field.name.to_owned(),
                swift_field: swift_ident(field.name),
                shape: field.shape(),
            })
            .collect()),
        VariantKind::Unit | VariantKind::Newtype { .. } => {
            Err(SwiftCodegenError::UnsupportedShape {
                shape: variant.name.to_owned(),
                reason: "variant has no aggregate payload".to_owned(),
            })
        }
    }
}

fn collect_named_shapes(service: &ServiceDescriptor) -> Vec<NamedShape> {
    fn visit(shape: &'static Shape, seen: &mut BTreeSet<String>, out: &mut Vec<NamedShape>) {
        match classify_shape(shape) {
            ShapeKind::Struct(StructInfo {
                name: Some(name),
                fields,
                ..
            }) if seen.insert(name.to_owned()) => {
                for field in fields {
                    visit(field.shape(), seen, out);
                }
                out.push(NamedShape {
                    name: name.to_upper_camel_case(),
                    shape,
                });
            }
            ShapeKind::Enum(EnumInfo {
                name: Some(name),
                variants,
            }) if seen.insert(name.to_owned()) => {
                for variant in variants {
                    match classify_variant(variant) {
                        VariantKind::Newtype { inner } => visit(inner, seen, out),
                        VariantKind::Tuple { fields } | VariantKind::Struct { fields } => {
                            for field in fields {
                                visit(field.shape(), seen, out);
                            }
                        }
                        VariantKind::Unit => {}
                    }
                }
                out.push(NamedShape {
                    name: name.to_upper_camel_case(),
                    shape,
                });
            }
            ShapeKind::List { element }
            | ShapeKind::Slice { element }
            | ShapeKind::Array { element, .. }
            | ShapeKind::Set { element }
            | ShapeKind::Option { inner: element }
            | ShapeKind::Tx { inner: element }
            | ShapeKind::Rx { inner: element }
            | ShapeKind::Pointer { pointee: element } => visit(element, seen, out),
            ShapeKind::Map { key, value } => {
                visit(key, seen, out);
                visit(value, seen, out);
            }
            ShapeKind::Tuple { elements } => {
                for element in elements {
                    visit(element.shape, seen, out);
                }
            }
            ShapeKind::TupleStruct { fields } => {
                for field in fields {
                    visit(field.shape(), seen, out);
                }
            }
            ShapeKind::Result { ok, err } => {
                visit(ok, seen, out);
                visit(err, seen, out);
            }
            _ => {}
        }
    }

    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for method in service.methods {
        for arg in method.args {
            visit(arg.shape, &mut seen, &mut out);
        }
        visit(method.return_shape, &mut seen, &mut out);
    }
    out
}

fn swift_type(shape: &'static Shape) -> Result<String, SwiftCodegenError> {
    if is_bytes(shape) {
        return Ok("[UInt8]".to_owned());
    }
    match classify_shape(shape) {
        ShapeKind::Scalar(ScalarType::Bool) => Ok("Bool".to_owned()),
        ShapeKind::Scalar(ScalarType::U8) => Ok("UInt8".to_owned()),
        ShapeKind::Scalar(ScalarType::U16) => Ok("UInt16".to_owned()),
        ShapeKind::Scalar(ScalarType::U32) => Ok("UInt32".to_owned()),
        ShapeKind::Scalar(ScalarType::U64) => Ok("UInt64".to_owned()),
        ShapeKind::Scalar(ScalarType::I32) => Ok("Int32".to_owned()),
        ShapeKind::Scalar(ScalarType::I64) => Ok("Int64".to_owned()),
        ShapeKind::Scalar(ScalarType::F64) => Ok("Double".to_owned()),
        ShapeKind::Scalar(ScalarType::Str | ScalarType::String | ScalarType::CowStr) => {
            Ok("String".to_owned())
        }
        ShapeKind::Option { inner } => Ok(format!("{}?", swift_type(inner)?)),
        ShapeKind::Struct(StructInfo {
            name: Some(name), ..
        })
        | ShapeKind::Enum(EnumInfo {
            name: Some(name), ..
        }) => Ok(name.to_upper_camel_case()),
        ShapeKind::Tx { .. } | ShapeKind::Rx { .. } => Ok("VoxSwiftChannel".to_owned()),
        _ => Err(unsupported(
            shape,
            "no Swift type spelling for this shape yet",
        )),
    }
}

fn swift_shape_type(shape: &'static Shape) -> Result<String, SwiftCodegenError> {
    match classify_shape(shape) {
        ShapeKind::Struct(StructInfo {
            name: Some(name), ..
        })
        | ShapeKind::Enum(EnumInfo {
            name: Some(name), ..
        }) => Ok(name.to_upper_camel_case()),
        _ => swift_type(shape),
    }
}

fn descriptor_fn_name(shape: &'static Shape) -> Result<String, SwiftCodegenError> {
    if is_bytes(shape) {
        return Ok("descriptorForBytes".to_owned());
    }
    match classify_shape(shape) {
        ShapeKind::Scalar(ScalarType::Bool) => Ok("descriptorForBool".to_owned()),
        ShapeKind::Scalar(ScalarType::U8) => Ok("descriptorForUInt8".to_owned()),
        ShapeKind::Scalar(ScalarType::U16) => Ok("descriptorForUInt16".to_owned()),
        ShapeKind::Scalar(ScalarType::U32) => Ok("descriptorForUInt32".to_owned()),
        ShapeKind::Scalar(ScalarType::U64) => Ok("descriptorForUInt64".to_owned()),
        ShapeKind::Scalar(ScalarType::I32) => Ok("descriptorForInt32".to_owned()),
        ShapeKind::Scalar(ScalarType::I64) => Ok("descriptorForInt64".to_owned()),
        ShapeKind::Scalar(ScalarType::F64) => Ok("descriptorForDouble".to_owned()),
        ShapeKind::Scalar(ScalarType::Str | ScalarType::String | ScalarType::CowStr) => {
            Ok("descriptorForString".to_owned())
        }
        ShapeKind::Option { inner } => Ok(format!(
            "descriptorForOptional{}",
            swift_type(inner)?
                .replace(['[', ']', '?', ' '], "")
                .to_upper_camel_case()
        )),
        ShapeKind::Tx { inner } => Ok(format!(
            "descriptorForTx{}",
            swift_type(inner)?
                .replace(['[', ']', '?', ' '], "")
                .to_upper_camel_case()
        )),
        ShapeKind::Rx { inner } => Ok(format!(
            "descriptorForRx{}",
            swift_type(inner)?
                .replace(['[', ']', '?', ' '], "")
                .to_upper_camel_case()
        )),
        ShapeKind::Struct(StructInfo {
            name: Some(name), ..
        })
        | ShapeKind::Enum(EnumInfo {
            name: Some(name), ..
        }) => Ok(format!("descriptorFor{}", name.to_upper_camel_case())),
        _ => Err(unsupported(
            shape,
            "no Swift descriptor function name for this shape yet",
        )),
    }
}

fn method_args_type(service: &ServiceDescriptor, method_name: &str) -> String {
    format!(
        "{}{}Args",
        service.service_name.to_upper_camel_case(),
        method_name.to_upper_camel_case()
    )
}

fn method_args_descriptor_name(service: &ServiceDescriptor, method_name: &str) -> String {
    format!(
        "descriptorFor{}{}Args",
        service.service_name.to_upper_camel_case(),
        method_name.to_upper_camel_case()
    )
}

fn concrete_or_synthetic_type_id(shape: &'static Shape) -> Result<String, SwiftCodegenError> {
    let extracted =
        extract_schemas(shape).map_err(|error| SwiftCodegenError::Schema(error.to_string()))?;
    match extracted.root {
        TypeRef::Concrete { type_id, ref args } if args.is_empty() => Ok(hex_u64(type_id.0)),
        _ => synthetic_type_id(shape, 0x5A1F_7000_0000_0000),
    }
}

fn synthetic_type_id(shape: &'static Shape, salt: u64) -> Result<String, SwiftCodegenError> {
    let extracted =
        extract_schemas(shape).map_err(|error| SwiftCodegenError::Schema(error.to_string()))?;
    let mut ids = Vec::new();
    extracted.root.collect_ids(&mut ids);
    let mut value = salt;
    for SchemaHash(id) in ids {
        value = value.rotate_left(7) ^ id;
    }
    Ok(hex_u64(value))
}

fn hex_u64(value: u64) -> String {
    format!("0x{value:016X}")
}

fn unsupported(shape: &'static Shape, reason: &str) -> SwiftCodegenError {
    SwiftCodegenError::UnsupportedShape {
        shape: shape.type_identifier.to_owned(),
        reason: reason.to_owned(),
    }
}

fn swift_ident(name: &str) -> String {
    let ident = name.to_lower_camel_case();
    match ident.as_str() {
        "class" | "deinit" | "enum" | "extension" | "func" | "import" | "init" | "let" | "nil"
        | "private" | "public" | "return" | "struct" | "switch" | "var" => {
            format!("`{ident}`")
        }
        _ => ident,
    }
}

#[cfg(test)]
mod tests {
    #![allow(dead_code)]

    use facet::Facet;
    use vox_types::{ServiceDescriptor, Tx, method_descriptor};

    use super::generate_service;

    #[derive(Facet)]
    struct SwiftCall {
        method: u32,
        nonce: u64,
        ratio: f64,
        title: String,
        note: Option<String>,
        payload: Vec<u8>,
        shape: SwiftShape,
        retry: Option<u16>,
        outcome: SwiftOutcome,
        output: Tx<u32>,
    }

    #[derive(Facet)]
    struct SwiftReply {
        message: String,
        retry: Option<u16>,
    }

    #[derive(Facet)]
    #[repr(u8)]
    enum SwiftOutcome {
        Accepted(String),
        Rejected(u32),
    }

    #[derive(Facet)]
    #[repr(u8)]
    enum SwiftShape {
        Circle { radius: f64 },
        Rectangle { width: f64, height: f64 },
        Point,
    }

    #[test]
    fn generated_swift_builds_binette_method_codecs_from_descriptors() {
        let submit =
            method_descriptor::<(SwiftCall,), SwiftReply>("SwiftCanary", "submit", &["call"], None);
        let methods = Box::leak(vec![submit].into_boxed_slice());
        let service = ServiceDescriptor {
            service_name: "SwiftCanary",
            methods,
            doc: None,
        };

        let generated = generate_service(&service).expect("swift generation should support canary");
        assert!(generated.contains("import VoxSwift"));
        assert!(generated.contains("public struct SwiftCall"));
        assert!(generated.contains("public init(method: UInt32, nonce: UInt64, ratio: Double"));
        assert!(generated.contains("binette_primitive_u64_type_id()"));
        assert!(generated.contains("binette_primitive_f64_type_id()"));
        assert!(generated.contains("binetteThunkOptionalStringRepresentation()"));
        assert!(generated.contains("public enum SwiftOutcome"));
        assert!(generated.contains("public enum SwiftShape"));
        assert!(generated.contains("case circle(radius: Double)"));
        assert!(generated.contains("private struct SwiftShapeCirclePayload"));
        assert!(generated.contains("public struct SwiftCanarySubmitArgs"));
        assert!(generated.contains("public init(call: SwiftCall)"));
        assert!(generated.contains("try VoxSwiftMethodCodec("));
        assert!(generated.contains("arena.tuple("));
        assert!(generated.contains("arena.structure("));
        assert!(generated.contains("arena.enumeration("));
        assert!(generated.contains("arena.bytes()"));
        assert!(generated.contains("binetteDirectOptionalU16Representation()"));
        assert!(generated.contains("kind: \"vox.channel\""));
        assert!(generated.contains("arena.externalMetadataString(\"tx\")"));
        assert!(generated.contains("case .accepted(_): return 0"));
        assert!(generated.contains("case .rejected(_): return 1"));
        assert!(
            !generated.contains("JSON"),
            "Swift generation must not use JSON descriptor handoff:\n{generated}"
        );
    }

    #[test]
    fn generated_swift_rejects_unsupported_optional_before_runtime() {
        #[derive(Facet)]
        struct BadCall {
            maybe: Option<bool>,
        }

        let submit = method_descriptor::<(BadCall,), ()>("BadSwift", "submit", &["call"], None);
        let methods = Box::leak(vec![submit].into_boxed_slice());
        let service = ServiceDescriptor {
            service_name: "BadSwift",
            methods,
            doc: None,
        };

        let error = generate_service(&service).expect_err("Option<Bool> is not supported yet");
        assert!(
            error
                .to_string()
                .contains("no Swift C ABI optional representation helper for this payload yet")
        );
    }
}
